// ARMS — biceps and triceps isolation family (elbow flexion/extension patterns).
// Tier 1 movements: full MovementDef + form checks, mostly side camera views.
// Angles follow mainstream strength-coaching standards for elbow range (curls
// flex the elbow toward ~45-50°; extensions lock out toward ~170°), widened
// slightly for single-camera landmark noise. All cues are practical form tips.

import {
  depthCheck,
  elbowDriftCheck,
  torsoStillCheck,
} from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, elbowTriplet } from "./_shared";

export const arms: ExerciseEntry[] = [
  // ---------------------------------------------------------------- bicep curl (existing)
  {
    meta: {
      slug: "bicep_curl",
      name: "Bicep Curl",
      aliases: ["bicep curl", "biceps curl", "dumbbell curl", "curl"],
      primaryMuscles: ["biceps"],
      secondaryMuscles: ["forearms"],
      equipment: ["dumbbell", "barbell", "band"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall with a weight in each hand, arms extended at your sides.",
        "Keep your elbows pinned close to your sides.",
        "Curl the weight up by bending at the elbow until your forearm is near vertical.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Keep your upper arms still and let only your forearms move.",
        "Straighten fully at the bottom for a consistent range each rep.",
        "Squeeze the biceps at the top rather than swinging the weight up.",
        "Control the lowering phase instead of dropping the weight.",
      ],
      commonMistakes: [
        "Swinging the torso to heave the weight up.",
        "Letting the elbows drift forward at the top.",
        "Cutting the bottom short and missing the full stretch.",
      ],
      romGuideline: "Elbow from nearly straight to about 45-55° at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "bicep-curl",
      name: "Bicep Curl",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells", "Barbell", "Bands"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side or front view, elbow to wrist visible",
      setupCue: "Stand tall with arms extended at your sides.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 158,
      activeAngle: 50,
      minRepFraction: 0.65,
      formChecks: [
        elbowDriftCheck("Keep your elbows pinned to your sides."),
        torsoStillCheck("Still torso — let only your forearms move.", 20),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Straighten fully at the bottom and squeeze at the top.",
    },
  },
  // ---------------------------------------------------------------- hammer curl
  {
    meta: {
      slug: "hammer_curl",
      name: "Hammer Curl",
      aliases: ["hammer curl", "neutral grip curl"],
      primaryMuscles: ["biceps", "forearms"],
      secondaryMuscles: [],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall with a dumbbell in each hand, palms facing your body.",
        "Keep your elbows tucked close to your sides.",
        "Curl the weights up while holding the neutral, thumbs-up grip.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Hold the neutral grip throughout so your palms stay facing in.",
        "Keep your upper arms still and move only at the elbow.",
        "Straighten fully at the bottom for a consistent range.",
        "Control the lowering phase on every rep.",
      ],
      commonMistakes: [
        "Swinging the body to lift the weight.",
        "Letting the elbows drift forward.",
        "Rushing the reps and cutting the range short.",
      ],
      romGuideline: "Elbow from nearly straight to about 45-55° at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "hammer-curl",
      name: "Hammer Curl",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side or front view, elbow to wrist visible",
      setupCue: "Stand tall with arms at your sides, palms facing in.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 158,
      activeAngle: 50,
      minRepFraction: 0.65,
      formChecks: [
        elbowDriftCheck("Keep your elbows pinned to your sides."),
        torsoStillCheck("Still torso — let only your forearms move.", 20),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Straighten fully at the bottom and squeeze at the top.",
    },
  },
  // ---------------------------------------------------------------- barbell curl
  {
    meta: {
      slug: "barbell_curl",
      name: "Barbell Curl",
      aliases: ["barbell curl", "straight bar curl"],
      primaryMuscles: ["biceps"],
      secondaryMuscles: ["forearms"],
      equipment: ["barbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall holding a barbell with an underhand, shoulder-width grip.",
        "Keep your elbows tucked close to your sides.",
        "Curl the bar up by bending at the elbows until your forearms are near vertical.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Keep your upper arms still and drive the movement from the elbows.",
        "Straighten fully at the bottom for a consistent range each rep.",
        "Squeeze at the top rather than swinging the bar up.",
        "Control the lowering phase instead of letting it drop.",
      ],
      commonMistakes: [
        "Rocking the torso to swing the bar up.",
        "Letting the elbows drift forward at the top.",
        "Bouncing out of the bottom without a full stretch.",
      ],
      romGuideline: "Elbow from nearly straight to about 45-50° at the top (front/side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "barbell-curl",
      name: "Barbell Curl",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Barbell"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front or side view, elbows to wrists visible",
      setupCue: "Stand tall holding the bar with arms extended.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 158,
      activeAngle: 48,
      minRepFraction: 0.65,
      formChecks: [
        elbowDriftCheck("Keep your elbows pinned to your sides."),
        torsoStillCheck("Still torso — let only your forearms move.", 20),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Straighten fully at the bottom and squeeze at the top.",
    },
  },
  // ---------------------------------------------------------------- concentration curl
  {
    meta: {
      slug: "concentration_curl",
      name: "Concentration Curl",
      aliases: ["concentration curl", "seated concentration curl"],
      primaryMuscles: ["biceps"],
      secondaryMuscles: [],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Sit on a bench and brace the back of your working arm against your inner thigh.",
        "Let the dumbbell hang with your arm fully extended.",
        "Curl the weight up by bending only at the elbow.",
        "Lower under control to a full stretch, then finish your reps and switch sides.",
      ],
      formPoints: [
        "Keep the upper arm braced against your thigh so only the forearm moves.",
        "Straighten fully at the bottom for the full range.",
        "Squeeze the biceps at the top of each rep.",
        "Control the lowering phase throughout.",
      ],
      commonMistakes: [
        "Lifting the elbow off the thigh to cheat the weight up.",
        "Cutting the bottom short and missing the stretch.",
        "Rushing the reps rather than controlling them.",
      ],
      romGuideline: "Elbow from fully straight to about 40-50° at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "concentration-curl",
      name: "Concentration Curl",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, seated with your working arm and the bench visible",
      setupCue: "Sit side-on and brace your arm against your inner thigh.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 160,
      activeAngle: 45,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Curl a little higher — squeeze at the top.", 0.7),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Keep the arm braced and use a full range each rep.",
    },
  },
  // ---------------------------------------------------------------- preacher curl
  {
    meta: {
      slug: "preacher_curl",
      name: "Preacher Curl",
      aliases: ["preacher curl", "preacher bench curl"],
      primaryMuscles: ["biceps"],
      secondaryMuscles: [],
      equipment: ["dumbbell", "barbell", "machine", "bench"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Rest the backs of your upper arms flat on the preacher pad.",
        "Let the weight hang with your arms fully extended.",
        "Curl the weight up by bending at the elbows.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Keep the backs of your arms flat on the pad throughout.",
        "Straighten fully at the bottom for the full range each rep.",
        "Squeeze at the top rather than swinging the weight up.",
        "Control the lowering phase and resist letting it drop.",
      ],
      commonMistakes: [
        "Lifting the arms off the pad at the top.",
        "Bouncing out of the bottom without a full stretch.",
        "Rushing the lowering phase.",
      ],
      romGuideline: "Elbow from fully straight to about 40-50° at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "preacher-curl",
      name: "Preacher Curl",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells", "Barbell", "Machine", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, upper arms and the preacher pad visible",
      setupCue: "Set your arms on the pad, side-on to the camera.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 160,
      activeAngle: 45,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Curl a touch higher — squeeze at the top.", 0.7),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Keep your arms on the pad and use a full range.",
    },
  },
  // ---------------------------------------------------------------- tricep dip (bench)
  {
    meta: {
      slug: "tricep_dip_bench",
      name: "Bench Tricep Dip",
      aliases: ["bench dip", "tricep dip", "bench tricep dip"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: ["shoulders", "chest"],
      equipment: ["bodyweight", "bench"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Sit on the edge of a bench and place your hands beside your hips.",
        "Slide your hips off the bench with your legs out in front.",
        "Lower your body by bending your elbows until they reach about 90°.",
        "Press back up until your arms are straight, then repeat.",
      ],
      formPoints: [
        "Keep your elbows pointing back rather than flaring out to the sides.",
        "Lower until your elbows reach about a right angle for a full range.",
        "Keep your hips close to the bench as you lower.",
        "Press up to a straight-arm finish each rep.",
      ],
      commonMistakes: [
        "Short reps that barely bend the elbows.",
        "Letting the elbows flare wide.",
        "Drifting the hips far away from the bench.",
      ],
      romGuideline: "Elbow bends to about 90° at the bottom, straight at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "tricep-dip-bench",
      name: "Bench Tricep Dip",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Bodyweight", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, shoulders to hands and the bench visible",
      setupCue: "Set your hands on the bench edge, side-on to the camera.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 168,
      activeAngle: 88,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Lower a little more — bend to about 90°.", 0.6),
      ],
      focus: ["depth", "control", "tempo"],
      reviewCue: "Lower to about 90° and press to a straight-arm finish.",
    },
  },
  // ---------------------------------------------------------------- overhead tricep extension
  {
    meta: {
      slug: "overhead_tricep_extension",
      name: "Overhead Tricep Extension",
      aliases: ["overhead tricep extension", "overhead triceps extension", "french press"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: [],
      equipment: ["dumbbell", "cable"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Hold a weight overhead with your arms extended and elbows close to your head.",
        "Keep your upper arms still and pointing up.",
        "Lower the weight behind your head by bending at the elbows.",
        "Extend back up until your arms are straight, then repeat.",
      ],
      formPoints: [
        "Keep your elbows pointing up and close to your head throughout.",
        "Lower to a full stretch behind your head for the full range.",
        "Extend fully to a straight-arm lockout at the top.",
        "Control the movement rather than letting the weight fall.",
      ],
      commonMistakes: [
        "Letting the elbows flare wide on the way up.",
        "Cutting the lockout short at the top.",
        "Rushing the lowering phase.",
      ],
      romGuideline: "Elbow from a deep bend behind the head to a straight lockout overhead (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "overhead-tricep-extension",
      name: "Overhead Tricep Extension",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells", "Cable"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, upper arms and elbows visible overhead",
      setupCue: "Stand side-on with the weight extended overhead.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 60,
      activeAngle: 168,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Extend all the way up until your arms are straight.", 0.7),
      ],
      focus: ["lockout", "control", "tempo"],
      reviewCue: "Stretch at the bottom and lock out fully at the top.",
    },
  },
  // ---------------------------------------------------------------- tricep kickback
  {
    meta: {
      slug: "tricep_kickback",
      name: "Tricep Kickback",
      aliases: ["tricep kickback", "triceps kickback", "dumbbell kickback"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: [],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Hinge forward with a flat back and pin your upper arm to your side.",
        "Start with your elbow bent and the weight hanging down.",
        "Extend at the elbow to straighten your arm behind you.",
        "Return under control to the bent-elbow start, then switch sides.",
      ],
      formPoints: [
        "Keep your upper arm still and level so only the forearm moves.",
        "Extend fully to a straight-arm finish behind you.",
        "Hold a steady flat-back position throughout.",
        "Control the return rather than letting the weight swing.",
      ],
      commonMistakes: [
        "Dropping the upper arm instead of keeping it pinned.",
        "Short reps that never reach full extension.",
        "Swinging the weight instead of controlling it.",
      ],
      romGuideline: "Elbow from a bent start to a straight lockout behind you (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "tricep-kickback",
      name: "Tricep Kickback",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 12, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Side view, hinged over with your working arm visible",
      setupCue: "Hinge forward side-on and pin your upper arm to your side.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 90,
      activeAngle: 172,
      minRepFraction: 0.65,
      formChecks: [
        depthCheck("Extend fully — straighten your arm behind you.", 0.65),
      ],
      focus: ["lockout", "control", "tempo"],
      reviewCue: "Keep your upper arm still and lock out each rep.",
    },
  },
  // ---------------------------------------------------------------- skull crusher
  {
    meta: {
      slug: "skull_crusher",
      name: "Skull Crusher",
      aliases: ["skull crusher", "lying tricep extension", "lying triceps extension"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: [],
      equipment: ["barbell", "dumbbell", "bench"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Lie on a bench holding the weight with your arms extended over your chest.",
        "Keep your upper arms pointing up and fairly still.",
        "Lower the weight toward your forehead by bending at the elbows.",
        "Extend back up to a straight-arm lockout, then repeat.",
      ],
      formPoints: [
        "Keep your upper arms pointing up and still so only the forearms move.",
        "Lower under control to a full stretch.",
        "Extend fully to a straight-arm lockout at the top.",
        "Keep the tempo smooth on both phases.",
      ],
      commonMistakes: [
        "Letting the elbows flare wide.",
        "Cutting the lockout short at the top.",
        "Rushing the lowering phase.",
      ],
      romGuideline: "Elbow from a deep bend near the forehead to a straight lockout (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "skull-crusher",
      name: "Skull Crusher",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Barbell", "Dumbbells", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, lying on the bench with your arms visible",
      setupCue: "Lie side-on to the camera with the weight over your chest.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 90,
      activeAngle: 172,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Extend all the way up until your arms are straight.", 0.7),
      ],
      focus: ["lockout", "control", "tempo"],
      reviewCue: "Control the stretch and lock out fully at the top.",
    },
  },
];
