// CONDITIONING & LOADED — TIER 3 exercises: metadata ONLY (no MovementDef).
// Machines, cables, isolation work, loaded carries, and conditioning where an
// honest single-camera setup can't usefully track the load path or rep count.
// Each entry is meta-only ({ meta }) — the app logs these by timer/manual entry.
// All coaching wording is practical (see AGENTS.md "Claim Safety").

import type { ExerciseEntry } from "../types";

export const conditioning: ExerciseEntry[] = [
  // ------------------------------------------------------------ leg extension
  {
    meta: {
      slug: "leg_extension",
      name: "Leg Extension",
      aliases: ["leg extension", "knee extension", "seated leg extension"],
      primaryMuscles: ["quads"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Sit in the machine with your back against the pad and knees lined up with the pivot point.",
        "Tuck your shins behind the roller pad so it rests just above your ankles.",
        "Grip the side handles and brace your torso against the seat.",
        "Extend your knees to straighten your legs, then lower under control back to the start.",
      ],
      formPoints: [
        "Line the machine pivot up with your knee joint before you start.",
        "Extend smoothly and pause briefly at the top rather than snapping into lockout.",
        "Lower with control instead of letting the weight drop back down.",
        "Keep your hips and back settled into the pad throughout.",
      ],
      commonMistakes: [
        "Using momentum to swing the weight up.",
        "Slamming the stack down on the lowering phase.",
        "Sliding the hips off the seat to gain leverage.",
      ],
      romGuideline: "From about 90° of knee bend to near-full extension, then back down.",
      tutTarget: [2, 4],
    },
  },
  // ------------------------------------------------------------ leg curl
  {
    meta: {
      slug: "leg_curl",
      name: "Leg Curl",
      aliases: ["leg curl", "hamstring curl", "seated leg curl", "lying leg curl"],
      primaryMuscles: ["hamstrings"],
      secondaryMuscles: ["calves"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Set up seated or lying so the roller pad sits just above your heels.",
        "Line your knees up with the machine's pivot and settle into the pads.",
        "Grip the handles and brace your torso to stay anchored.",
        "Curl your heels toward your glutes, then return slowly to the start.",
      ],
      formPoints: [
        "Match the pad position to your leg length so the pivot tracks your knee.",
        "Curl with a smooth squeeze rather than a jerk off the bottom.",
        "Control the return so the hamstrings stay loaded on the way back.",
        "Keep your hips pressed down instead of arching up off the bench.",
      ],
      commonMistakes: [
        "Bouncing the weight out of the bottom position.",
        "Letting the hips lift to help pull the weight.",
        "Rushing the lowering phase.",
      ],
      romGuideline: "From near-straight legs to a full heel-toward-glute curl, then controlled back.",
      tutTarget: [2, 4],
    },
  },
  // ------------------------------------------------------------ seated calf raise
  {
    meta: {
      slug: "seated_calf_raise",
      name: "Seated Calf Raise",
      aliases: ["seated calf raise", "seated calf", "soleus raise"],
      primaryMuscles: ["calves"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Sit in the machine and place the balls of your feet on the platform.",
        "Rest the thigh pad snugly across your lower thighs.",
        "Release the safety catch and let your heels drop for a stretch.",
        "Press up onto the balls of your feet, then lower under control.",
      ],
      formPoints: [
        "Let the heels drop for a full stretch at the bottom of each rep.",
        "Press all the way up onto the balls of your feet at the top.",
        "Move at a steady tempo rather than bouncing off the stretch.",
        "Keep the balls of your feet planted so your foot doesn't roll outward.",
      ],
      commonMistakes: [
        "Cutting the range short at the top or bottom.",
        "Bouncing quickly through partial reps.",
        "Letting the feet roll to the outside edge.",
      ],
      romGuideline: "From a full heel-dropped stretch up to a tall press on the balls of the feet.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ hip abduction machine
  {
    meta: {
      slug: "hip_abduction_machine",
      name: "Hip Abduction Machine",
      aliases: ["hip abduction", "abductor machine", "outer thigh machine"],
      primaryMuscles: ["abductors", "glutes"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Sit in the machine with the outside of your knees against the pads.",
        "Set the starting width so your knees begin close together.",
        "Hold the handles and sit tall against the backrest.",
        "Press your knees outward against the pads, then return slowly to the middle.",
      ],
      formPoints: [
        "Sit tall and keep your back against the pad through the whole rep.",
        "Push out to a controlled end range rather than forcing it wide.",
        "Resist the return so the outer hips stay working on the way in.",
        "Keep your feet and knees moving together as one unit.",
      ],
      commonMistakes: [
        "Leaning forward to throw the weight open.",
        "Letting the pads snap shut on the return.",
        "Using a jerky, fast tempo.",
      ],
      romGuideline: "From knees together to a comfortable spread, then controlled back to center.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ hip adduction machine
  {
    meta: {
      slug: "hip_adduction_machine",
      name: "Hip Adduction Machine",
      aliases: ["hip adduction", "adductor machine", "inner thigh machine"],
      primaryMuscles: ["adductors"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Sit in the machine with the inside of your knees against the pads.",
        "Set the starting width so your knees begin comfortably apart.",
        "Hold the handles and sit tall against the backrest.",
        "Squeeze your knees together against the pads, then return slowly to the open position.",
      ],
      formPoints: [
        "Set a start width you can control rather than the widest setting.",
        "Squeeze the knees together with a smooth, even effort.",
        "Resist the pads on the way back out to stay under load.",
        "Keep your torso settled against the backrest throughout.",
      ],
      commonMistakes: [
        "Starting from too wide a stretch and snapping shut.",
        "Letting the pads pull your legs open quickly on the return.",
        "Rocking the torso to help move the weight.",
      ],
      romGuideline: "From knees apart to fully squeezed together, then controlled back out.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ cable crunch
  {
    meta: {
      slug: "cable_crunch",
      name: "Cable Crunch",
      aliases: ["cable crunch", "kneeling cable crunch", "rope crunch"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["obliques"],
      equipment: ["cable"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "external",
      instructions: [
        "Attach a rope to a high pulley and kneel facing the stack.",
        "Hold the rope ends near your head or by your ears.",
        "Set your hips back slightly and brace your core.",
        "Crunch your ribs toward your pelvis, then return slowly to the tall start.",
      ],
      formPoints: [
        "Drive the movement by curling your ribs toward your hips, not by bending at the hips.",
        "Keep your hips roughly fixed so the abs do the work.",
        "Return slowly to a tall spine rather than letting the stack yank you up.",
        "Hold the rope steady near your head so your arms stay out of it.",
      ],
      commonMistakes: [
        "Turning it into a hip hinge instead of a spinal crunch.",
        "Pulling with the arms rather than the abs.",
        "Letting the weight pull you back up too fast.",
      ],
      romGuideline: "From a tall kneeling spine to a rounded crunch, then controlled back up.",
      tutTarget: [2, 4],
    },
  },
  // ------------------------------------------------------------ cable woodchop
  {
    meta: {
      slug: "cable_woodchop",
      name: "Cable Woodchop",
      aliases: ["cable woodchop", "woodchopper", "cable chop"],
      primaryMuscles: ["obliques", "core"],
      secondaryMuscles: ["shoulders", "glutes"],
      equipment: ["cable"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "external",
      instructions: [
        "Set the pulley high and stand side-on with a handle in both hands.",
        "Step out so there is tension and set a shoulder-width stance.",
        "Brace your core and start with arms up toward the pulley.",
        "Pull the handle down and across your body to the opposite hip, then return under control.",
      ],
      formPoints: [
        "Rotate through your trunk and hips together rather than only yanking with the arms.",
        "Keep your arms fairly straight so the torso drives the motion.",
        "Pivot the back foot as you rotate to let the hips follow.",
        "Control the return so it doesn't snap you back around.",
      ],
      commonMistakes: [
        "Bending the elbows and turning it into an arm pull.",
        "Keeping the feet locked so the low back does the twisting.",
        "Rushing the return and losing tension.",
      ],
      romGuideline: "From high on one side down and across to the opposite hip, then controlled back.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ cable bicep curl
  {
    meta: {
      slug: "cable_bicep_curl",
      name: "Cable Bicep Curl",
      aliases: ["cable curl", "cable bicep curl", "cable biceps curl"],
      primaryMuscles: ["biceps"],
      secondaryMuscles: ["forearms"],
      equipment: ["cable"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Attach a bar or handle to a low pulley and stand facing the stack.",
        "Hold the attachment with palms up and let your arms hang.",
        "Set your elbows near your sides and brace your torso.",
        "Curl the attachment up toward your shoulders, then lower slowly to full extension.",
      ],
      formPoints: [
        "Keep your elbows tucked near your sides as fixed pivots.",
        "Curl with a smooth squeeze and pause briefly near the top.",
        "Lower all the way to a straight-arm stretch each rep.",
        "Keep your torso upright rather than swinging to help.",
      ],
      commonMistakes: [
        "Swinging the torso to fling the weight up.",
        "Letting the elbows drift forward and out.",
        "Cutting the lowering phase short.",
      ],
      romGuideline: "From arms straight to a full curl toward the shoulders, then controlled back down.",
      tutTarget: [2, 4],
    },
  },
  // ------------------------------------------------------------ cable tricep pushdown
  {
    meta: {
      slug: "cable_tricep_pushdown",
      name: "Cable Tricep Pushdown",
      aliases: ["tricep pushdown", "cable pushdown", "rope pushdown", "triceps pushdown"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: [],
      equipment: ["cable"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Attach a bar or rope to a high pulley and stand facing the stack.",
        "Grip the attachment and pull it down until your elbows sit at your sides.",
        "Set a slight forward lean and brace your core.",
        "Press the attachment down to straight arms, then let it rise back under control.",
      ],
      formPoints: [
        "Pin your elbows at your sides so only the forearms move.",
        "Press down to full extension and squeeze briefly at the bottom.",
        "Let the weight rise under control to a stretched start.",
        "Keep a stable, slightly forward torso rather than leaning into each rep.",
      ],
      commonMistakes: [
        "Letting the elbows flare out and drift up.",
        "Leaning heavily to push the weight with body weight.",
        "Cutting the range short at the top or bottom.",
      ],
      romGuideline: "From elbows bent near 90° down to fully straight arms, then controlled back up.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ cable lateral raise
  {
    meta: {
      slug: "cable_lateral_raise",
      name: "Cable Lateral Raise",
      aliases: ["cable lateral raise", "cable side raise", "cable lateral"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["traps"],
      equipment: ["cable"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "external",
      instructions: [
        "Set a low pulley and stand side-on with the handle in the far hand.",
        "Let the working arm hang across the front of your body.",
        "Set a slight bend in the elbow and brace your torso.",
        "Raise the handle out to about shoulder height, then lower slowly across your body.",
      ],
      formPoints: [
        "Lead with your elbow and wrist rising together to about shoulder height.",
        "Keep a soft, fixed elbow bend rather than curling the arm.",
        "Lower slowly across the body to keep tension on the side delt.",
        "Stay tall and avoid shrugging the shoulder up toward your ear.",
      ],
      commonMistakes: [
        "Swinging the torso to launch the arm up.",
        "Shrugging the trap to lift instead of the shoulder.",
        "Dropping the arm quickly and losing tension.",
      ],
      romGuideline: "From arm hanging across the body up to about shoulder height, then controlled back.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ glute kickback machine
  {
    meta: {
      slug: "glute_kickback_machine",
      name: "Glute Kickback Machine",
      aliases: ["glute kickback", "kickback machine", "cable kickback"],
      primaryMuscles: ["glutes"],
      secondaryMuscles: ["hamstrings"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Set up on the machine with your torso supported and one foot on the platform.",
        "Line your working hip up with the machine's pivot.",
        "Brace your core and hold the support handles.",
        "Press your working leg back and up to extend the hip, then return under control.",
      ],
      formPoints: [
        "Drive the movement from the glute by extending the hip.",
        "Squeeze briefly at the top rather than swinging past your range.",
        "Return slowly so the glute stays loaded on the way back.",
        "Keep your torso and low back stable instead of arching to reach.",
      ],
      commonMistakes: [
        "Arching the low back to push the leg higher.",
        "Swinging the leg with momentum.",
        "Rushing the return phase.",
      ],
      romGuideline: "From hip flexed at the start to a controlled hip extension, then back down.",
      tutTarget: [2, 3],
    },
  },
  // ------------------------------------------------------------ back extension
  {
    meta: {
      slug: "back_extension",
      name: "Back Extension",
      aliases: ["back extension", "hyperextension", "45 degree back extension"],
      primaryMuscles: ["lower_back", "glutes"],
      secondaryMuscles: ["hamstrings"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "both",
      instructions: [
        "Set the pad just below your hip crease and anchor your feet.",
        "Cross your arms over your chest or hold a light weight to your chest.",
        "Start bent forward at the hips with a long spine.",
        "Extend up until your torso lines up with your legs, then lower under control.",
      ],
      formPoints: [
        "Set the pad below the hip crease so you can hinge freely.",
        "Extend up to a straight line rather than arching well past it.",
        "Lead the rise with your glutes and hamstrings.",
        "Lower slowly with a long spine rather than dropping down.",
      ],
      commonMistakes: [
        "Cranking into a big backward arch at the top.",
        "Bouncing at the bottom of each rep.",
        "Rounding hard and yanking up with the low back.",
      ],
      romGuideline: "From a forward hinge up to torso in line with the legs, then controlled back down.",
      tutTarget: [2, 4],
    },
  },
  // ------------------------------------------------------------ ab wheel rollout
  {
    meta: {
      slug: "ab_wheel_rollout",
      name: "Ab Wheel Rollout",
      aliases: ["ab wheel", "ab rollout", "ab wheel rollout", "wheel rollout"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["obliques", "lats", "shoulders"],
      equipment: ["bodyweight"],
      difficulty: "advanced",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Kneel and grip the ab wheel on the floor under your shoulders.",
        "Brace your core hard and set your ribs down toward your hips.",
        "Roll the wheel forward, letting your body extend into a long line.",
        "Roll out only as far as you can stay braced, then pull back to the start.",
      ],
      formPoints: [
        "Keep your core braced so your hips and ribs move as one unit.",
        "Roll out only to a range where you can keep a flat, stable midsection.",
        "Pull back by drawing the wheel in, not by piking at the hips.",
        "Start from your knees and extend range as your control improves.",
      ],
      commonMistakes: [
        "Letting the low back sag as the wheel rolls out.",
        "Rolling out farther than you can control and collapsing.",
        "Piking at the hips instead of pulling with a braced trunk.",
      ],
      romGuideline: "Roll out to a comfortably long, braced position, then return to a tucked start.",
      tutTarget: [2, 4],
    },
  },
  // ------------------------------------------------------------ farmer carry
  {
    meta: {
      slug: "farmer_carry",
      name: "Farmer Carry",
      aliases: ["farmer carry", "farmer's walk", "farmers walk", "loaded carry"],
      primaryMuscles: ["forearms", "traps", "core"],
      secondaryMuscles: ["full_body", "glutes", "quads"],
      equipment: ["dumbbell", "kettlebell"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Set a matched weight at each side and stand between them.",
        "Hinge down, grip both handles firmly, and stand up tall.",
        "Set your shoulders back and brace your core.",
        "Walk for the set distance or time with smooth, even steps, then set the weights down.",
      ],
      formPoints: [
        "Stand tall with shoulders back rather than hunching over the load.",
        "Keep your core braced so your torso stays steady as you walk.",
        "Take controlled, even steps instead of rushing.",
        "Grip firmly and keep the weights from swinging into your legs.",
      ],
      commonMistakes: [
        "Rounding the upper back under the load.",
        "Letting the weights sway and knock the legs.",
        "Shuffling too fast and losing an upright posture.",
      ],
      romGuideline: "Carry for the set distance or time keeping a tall, braced torso.",
    },
  },
  // ------------------------------------------------------------ suitcase carry
  {
    meta: {
      slug: "suitcase_carry",
      name: "Suitcase Carry",
      aliases: ["suitcase carry", "single arm carry", "unilateral carry"],
      primaryMuscles: ["obliques", "forearms", "core"],
      secondaryMuscles: ["traps", "glutes"],
      equipment: ["dumbbell", "kettlebell"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Set one weight beside you and stand next to it.",
        "Hinge down, grip the handle, and stand up tall.",
        "Brace your core and level your shoulders and hips.",
        "Walk for the set distance or time resisting the lean, then switch sides.",
      ],
      formPoints: [
        "Keep your shoulders and hips level rather than leaning toward the weight.",
        "Brace hard on the side opposite the load to stay upright.",
        "Take smooth, even steps and keep your ribs stacked over your hips.",
        "Carry each side for a matched distance or time.",
      ],
      commonMistakes: [
        "Leaning sideways toward the loaded hand.",
        "Letting the shoulder hike up under the weight.",
        "Rushing and tipping off balance.",
      ],
      romGuideline: "Carry for the set distance or time keeping shoulders and hips level.",
    },
  },
  // ------------------------------------------------------------ overhead carry
  {
    meta: {
      slug: "overhead_carry",
      name: "Overhead Carry",
      aliases: ["overhead carry", "waiter carry", "overhead walk"],
      primaryMuscles: ["shoulders", "core"],
      secondaryMuscles: ["traps", "full_body"],
      equipment: ["dumbbell", "kettlebell"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "external",
      instructions: [
        "Press one or two weights overhead to a locked, stable position.",
        "Set your ribs down and brace your core under the load.",
        "Keep the weight stacked over your shoulder and midfoot.",
        "Walk for the set distance or time with steady steps, then lower under control.",
      ],
      formPoints: [
        "Keep the weight stacked over your shoulder rather than drifting forward.",
        "Brace your core and keep your ribs down instead of arching the low back.",
        "Take smooth steps and keep the overhead arm steady.",
        "Lower the weight with control once the carry is done.",
      ],
      commonMistakes: [
        "Letting the low back arch to hold the weight up.",
        "Allowing the weight to drift out of a stacked position.",
        "Losing balance by walking too quickly.",
      ],
      romGuideline: "Carry overhead for the set distance or time keeping the arm stacked and torso braced.",
    },
  },
  // ------------------------------------------------------------ sled push
  {
    meta: {
      slug: "sled_push",
      name: "Sled Push",
      aliases: ["sled push", "prowler push", "prowler"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["full_body", "calves", "core"],
      equipment: ["machine"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "external",
      instructions: [
        "Load the sled and grip the high or low handles.",
        "Set a strong forward lean with arms extended and core braced.",
        "Drive one leg back into the floor and step forward.",
        "Push for the set distance or time with powerful, driving steps.",
      ],
      formPoints: [
        "Set a forward lean and keep your arms extended so your legs drive the sled.",
        "Push through the whole foot with each driving step.",
        "Keep your core braced and your torso in a straight line.",
        "Aim for steady, powerful steps over the set distance.",
      ],
      commonMistakes: [
        "Standing too upright and losing driving leverage.",
        "Taking tiny choppy steps instead of full leg drives.",
        "Letting the hips sag or the back round.",
      ],
      romGuideline: "Push for the set distance or time with a braced torso and driving leg steps.",
    },
  },
  // ------------------------------------------------------------ sled pull
  {
    meta: {
      slug: "sled_pull",
      name: "Sled Pull",
      aliases: ["sled pull", "sled drag", "backward sled drag"],
      primaryMuscles: ["back", "hamstrings"],
      secondaryMuscles: ["full_body", "quads", "biceps"],
      equipment: ["machine"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "external",
      instructions: [
        "Attach a strap or handles to the sled and take up the slack.",
        "Set your stance and brace your core against the load.",
        "Pull the sled toward you with your back and arms, or walk it backward.",
        "Keep working for the set distance or time with steady effort.",
      ],
      formPoints: [
        "Drive through your legs while pulling with your back and arms together.",
        "Keep your core braced so the torso stays steady under tension.",
        "Take controlled steps and keep tension on the strap.",
        "Keep your chest up rather than rounding hard against the load.",
      ],
      commonMistakes: [
        "Rounding the back and yanking with the arms alone.",
        "Losing tension by letting the strap go slack.",
        "Rushing and stumbling on the footing.",
      ],
      romGuideline: "Pull or drag for the set distance or time keeping a braced, upright torso.",
    },
  },
  // ------------------------------------------------------------ yoke carry
  {
    meta: {
      slug: "yoke_carry",
      name: "Yoke Carry",
      aliases: ["yoke carry", "yoke walk", "yoke"],
      primaryMuscles: ["full_body"],
      secondaryMuscles: ["core", "traps", "quads", "glutes"],
      equipment: ["machine"],
      difficulty: "advanced",
      tier: 3,
      loadType: "external",
      instructions: [
        "Step under the yoke and set the crossbar across your upper back.",
        "Grip the frame, brace your whole torso, and stand it up.",
        "Set your shoulders back and take a stable stance.",
        "Walk for the set distance or time with short, controlled steps, then set it down.",
      ],
      formPoints: [
        "Brace your whole torso before you lift the yoke off the pins.",
        "Take short, controlled steps to keep the load stable.",
        "Keep your chest up and shoulders back under the crossbar.",
        "Set it down under control once you finish the distance.",
      ],
      commonMistakes: [
        "Taking long strides that let the yoke sway.",
        "Rounding forward under the crossbar.",
        "Losing the brace and letting the load bounce.",
      ],
      romGuideline: "Carry for the set distance or time with short, controlled steps and a braced torso.",
    },
  },
  // ------------------------------------------------------------ rowing machine
  {
    meta: {
      slug: "rowing_machine",
      name: "Rowing Machine",
      aliases: ["rowing machine", "erg", "rower", "indoor rowing"],
      primaryMuscles: ["full_body", "back"],
      secondaryMuscles: ["quads", "hamstrings", "biceps"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Strap your feet in and take the handle with an overhand grip.",
        "Start at the catch with shins vertical and arms reaching forward.",
        "Drive with your legs, then swing the torso back and pull the handle to your ribs.",
        "Reverse the order — arms, torso, then legs — to return to the catch.",
      ],
      formPoints: [
        "Sequence the drive legs, then back, then arms for a smooth stroke.",
        "Return in reverse order so the recovery stays relaxed and even.",
        "Keep a steady stroke rate rather than rushing the slide forward.",
        "Finish each stroke by drawing the handle to your lower ribs.",
      ],
      commonMistakes: [
        "Yanking with the arms before the legs drive.",
        "Rounding the back hard at the finish.",
        "Rushing the recovery back to the catch.",
      ],
      romGuideline: "Repeat full strokes at a steady stroke rate for the set time or distance.",
    },
  },
  // ------------------------------------------------------------ assault bike
  {
    meta: {
      slug: "assault_bike",
      name: "Assault Bike",
      aliases: ["assault bike", "air bike", "fan bike", "echo bike"],
      primaryMuscles: ["full_body", "quads"],
      secondaryMuscles: ["shoulders", "back", "core"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Set the seat height so your knees have a slight bend at the bottom.",
        "Take the moving handles and settle into an upright posture.",
        "Push and pull the handles while driving the pedals.",
        "Hold a steady cadence for the set time or intervals.",
      ],
      formPoints: [
        "Coordinate the arm push-pull with the leg drive for a smooth rhythm.",
        "Sit tall and keep your core engaged rather than slumping.",
        "Hold a cadence you can sustain for the target effort.",
        "Set seat height so your legs move through a comfortable range.",
      ],
      commonMistakes: [
        "Slumping over the handles as fatigue sets in.",
        "Going out too hard and cadence crashing.",
        "Setting the seat so high or low the legs feel cramped.",
      ],
      romGuideline: "Hold a steady cadence for the set time, distance, or intervals.",
    },
  },
  // ------------------------------------------------------------ treadmill run
  {
    meta: {
      slug: "treadmill_run",
      name: "Treadmill Run",
      aliases: ["treadmill run", "treadmill", "running", "treadmill jog"],
      primaryMuscles: ["quads", "hamstrings", "calves"],
      secondaryMuscles: ["full_body", "glutes", "core"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Clip the safety key and start the belt at an easy walking speed.",
        "Bring the pace up gradually to your target running speed.",
        "Run tall with a relaxed upper body and steady arm swing.",
        "Hold your pace for the set time or distance, then cool down at a walk.",
      ],
      formPoints: [
        "Run tall with a relaxed torso and easy arm swing.",
        "Aim for a steady cadence rather than long, heavy strides.",
        "Land with your feet under you instead of reaching far ahead.",
        "Ease into and out of the run with a warm-up and cool-down.",
      ],
      commonMistakes: [
        "Holding the rails and altering your natural stride.",
        "Starting too fast and fading early.",
        "Overstriding and landing heavily.",
      ],
      romGuideline: "Hold a steady running cadence for the set time or distance.",
    },
  },
  // ------------------------------------------------------------ stationary bike
  {
    meta: {
      slug: "stationary_bike",
      name: "Stationary Bike",
      aliases: ["stationary bike", "exercise bike", "spin bike", "indoor cycling"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "calves"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Set the seat height so your knee has a slight bend at the bottom of the stroke.",
        "Adjust the handlebars to a comfortable reach.",
        "Set a resistance level you can pedal smoothly against.",
        "Hold a steady cadence for the set time or intervals.",
      ],
      formPoints: [
        "Set seat height so your knee stays slightly bent at the bottom.",
        "Pedal in smooth, even circles rather than mashing straight down.",
        "Keep a relaxed grip and an upright, steady torso.",
        "Choose resistance and cadence you can hold for the target effort.",
      ],
      commonMistakes: [
        "Setting the seat too low and cramping the knees.",
        "Rocking the hips side to side under high resistance.",
        "Gripping the bars tightly and tensing the upper body.",
      ],
      romGuideline: "Hold a steady cadence and resistance for the set time or intervals.",
    },
  },
  // ------------------------------------------------------------ stair climber
  {
    meta: {
      slug: "stair_climber",
      name: "Stair Climber",
      aliases: ["stair climber", "stairmaster", "stepmill", "stair machine"],
      primaryMuscles: ["glutes", "quads", "calves"],
      secondaryMuscles: ["hamstrings", "full_body"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Step on and set a pace you can hold with an upright posture.",
        "Rest your hands lightly on the rails for balance only.",
        "Step through the full height of each stair.",
        "Hold a steady cadence for the set time or intervals.",
      ],
      formPoints: [
        "Stand tall and use the rails only for light balance.",
        "Take full steps and drive through the whole foot.",
        "Keep a cadence you can sustain rather than sprinting the steps.",
        "Let the glutes and quads drive each step up.",
      ],
      commonMistakes: [
        "Leaning heavily on the rails to offload the legs.",
        "Taking tiny partial steps.",
        "Hunching forward over the console.",
      ],
      romGuideline: "Step through the full stair height at a steady cadence for the set time.",
    },
  },
  // ------------------------------------------------------------ jump rope
  {
    meta: {
      slug: "jump_rope",
      name: "Jump Rope",
      aliases: ["jump rope", "skipping", "skip rope", "jumping rope"],
      primaryMuscles: ["calves", "full_body"],
      secondaryMuscles: ["shoulders", "forearms", "core"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Set the rope length so the handles reach about armpit height when stood on.",
        "Hold the handles at your sides with your elbows close in.",
        "Turn the rope with your wrists and hop just enough to clear it.",
        "Keep a steady rhythm for the set time or rounds.",
      ],
      formPoints: [
        "Turn the rope with your wrists rather than big arm circles.",
        "Hop just high enough to clear the rope and stay light on your feet.",
        "Land softly through the balls of your feet.",
        "Keep a relaxed, upright posture and a steady rhythm.",
      ],
      commonMistakes: [
        "Jumping much higher than needed and tiring quickly.",
        "Swinging from the shoulders instead of the wrists.",
        "Landing heavily flat-footed.",
      ],
      romGuideline: "Maintain a steady skipping rhythm for the set time or rounds.",
    },
  },
  // ------------------------------------------------------------ battle ropes
  {
    meta: {
      slug: "battle_ropes",
      name: "Battle Ropes",
      aliases: ["battle ropes", "battle rope", "rope waves", "battling ropes"],
      primaryMuscles: ["shoulders", "core", "full_body"],
      secondaryMuscles: ["forearms", "back"],
      equipment: ["machine"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Grip one rope end in each hand and step back to take up the slack.",
        "Set a shoulder-width stance with a slight knee bend and braced core.",
        "Drive waves down the ropes by moving your arms up and down.",
        "Keep the waves going for the set time or intervals.",
      ],
      formPoints: [
        "Keep a braced athletic stance with a slight knee bend throughout.",
        "Drive the waves from your shoulders and core, not just the wrists.",
        "Hold a rhythm you can sustain for the target interval.",
        "Keep your torso stable rather than rocking wildly with each wave.",
      ],
      commonMistakes: [
        "Standing upright with locked knees and losing power.",
        "Going all-out and stalling before the interval ends.",
        "Only flicking the wrists so the waves die out.",
      ],
      romGuideline: "Drive continuous waves for the set time or intervals from a braced stance.",
    },
  },
  // ------------------------------------------------------------ box jump
  {
    meta: {
      slug: "box_jump",
      name: "Box Jump",
      aliases: ["box jump", "box jumps", "plyo box jump"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["calves", "hamstrings", "core"],
      equipment: ["box"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Stand a short step back from a stable box at a height you can clear comfortably.",
        "Dip into a quarter squat and swing your arms back.",
        "Drive up and forward, landing softly on top of the box in a partial squat.",
        "Stand tall on the box, then step down one foot at a time and reset.",
      ],
      formPoints: [
        "Pick a box height you can land on softly and in control.",
        "Land quietly in a partial squat with your whole foot on the box.",
        "Use your arm swing to help drive the jump.",
        "Step down rather than jumping down to reset each rep.",
      ],
      commonMistakes: [
        "Choosing a box too tall to land on cleanly.",
        "Landing with stiff, straight legs.",
        "Jumping back down and rushing the next rep.",
      ],
      romGuideline: "From a quarter-squat dip to a soft landing on the box, resetting between reps.",
      tutTarget: [1, 3],
    },
  },
  // ------------------------------------------------------------ burpee
  {
    meta: {
      slug: "burpee",
      name: "Burpee",
      aliases: ["burpee", "burpees", "squat thrust"],
      primaryMuscles: ["full_body"],
      secondaryMuscles: ["chest", "quads", "core", "shoulders"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Start standing, then squat down and place your hands on the floor.",
        "Jump or step your feet back into a plank position.",
        "Lower your chest to the floor, then press back up.",
        "Jump or step your feet back in and stand or hop up to finish the rep.",
      ],
      formPoints: [
        "Keep your core braced so your hips stay in line during the plank.",
        "Move through a smooth sequence rather than collapsing to the floor.",
        "Land softly on the hop up with a slight knee bend.",
        "Step the feet in and out if hopping feels too much for the set.",
      ],
      commonMistakes: [
        "Letting the hips sag when the feet kick back.",
        "Belly-flopping to the floor instead of lowering with control.",
        "Landing stiff-legged on the jump up.",
      ],
      romGuideline: "One full cycle: stand, floor contact, plank, and back to a standing finish.",
      tutTarget: [1, 3],
    },
  },
  // ------------------------------------------------------------ medicine ball slam
  {
    meta: {
      slug: "medicine_ball_slam",
      name: "Medicine Ball Slam",
      aliases: ["medicine ball slam", "med ball slam", "ball slam", "slam ball"],
      primaryMuscles: ["core", "shoulders", "full_body"],
      secondaryMuscles: ["back", "lats"],
      equipment: ["medicine_ball"],
      difficulty: "beginner",
      tier: 3,
      loadType: "external",
      instructions: [
        "Stand with feet about shoulder-width apart holding a slam ball.",
        "Reach the ball overhead as you extend your body tall.",
        "Slam the ball down in front of you, hinging at the hips.",
        "Pick the ball back up and reset for the next rep.",
      ],
      formPoints: [
        "Reach tall overhead, then drive the slam with your core and hips.",
        "Hinge at the hips as you bring the ball down rather than only rounding.",
        "Follow the ball down with your eyes and stay balanced.",
        "Reset your stance and grip before the next rep.",
      ],
      commonMistakes: [
        "Slamming with the arms only and skipping the hip drive.",
        "Rounding hard at the low back instead of hinging.",
        "Rushing to grab the ball and losing balance.",
      ],
      romGuideline: "From a tall overhead reach to a full downward slam, resetting between reps.",
      tutTarget: [1, 2],
    },
  },
  // ------------------------------------------------------------ turkish get-up
  {
    meta: {
      slug: "kettlebell_turkish_getup",
      name: "Kettlebell Turkish Get-Up",
      aliases: ["turkish get-up", "turkish getup", "get up", "tgu", "kettlebell get-up"],
      primaryMuscles: ["full_body", "core"],
      secondaryMuscles: ["shoulders", "glutes", "obliques"],
      equipment: ["kettlebell"],
      difficulty: "advanced",
      tier: 3,
      loadType: "external",
      instructions: [
        "Lie on your back and press the kettlebell up with one arm locked out.",
        "Bend the same-side knee and roll onto your opposite forearm, then hand.",
        "Bridge your hips up, sweep your straight leg through, and come to a kneel.",
        "Stand up keeping the bell locked overhead, then reverse each step to lie back down.",
      ],
      formPoints: [
        "Keep your eyes on the bell and the arm locked out through the early steps.",
        "Move through one position at a time rather than rushing the sequence.",
        "Keep the loaded shoulder packed and stable at every stage.",
        "Reverse the steps in order to return under control.",
      ],
      commonMistakes: [
        "Bending the loaded arm and letting the bell drift.",
        "Rushing between positions and losing the stacked shoulder.",
        "Skipping steps in the sequence.",
      ],
      romGuideline: "Move from lying to standing and back through each get-up position, one side at a time.",
    },
  },
];
