// CORE — trunk flexion, anti-extension, and anti-rotation work.
// Planks run in hold mode (body-line angle scored over time). Crunch/leg-raise
// style movements use trunk/hip flexion angle as the rep driver.

import { bodyLineCheck, depthCheck } from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, hipTriplet, bodyTriplet } from "./_shared";

export const core: ExerciseEntry[] = [
  // ---------------------------------------------------------------- front plank (existing)
  {
    meta: {
      slug: "front_plank",
      name: "Front Plank",
      aliases: ["plank", "front plank", "forearm plank"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["obliques", "shoulders", "glutes"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Set your forearms on the floor under your shoulders.",
        "Extend your legs back and rise onto your toes.",
        "Form one straight line from your shoulders through your hips to your ankles.",
        "Brace your core and hold the position for time.",
      ],
      formPoints: [
        "Hold a straight line — hips level with your shoulders, not sagging or piked.",
        "Squeeze your glutes and brace your midsection.",
        "Keep your neck long and your gaze just ahead of your hands.",
        "Breathe steadily rather than holding your breath.",
      ],
      commonMistakes: [
        "Letting the hips sag toward the floor.",
        "Piking the hips up to make it easier.",
        "Dropping the head or shrugging the shoulders.",
      ],
      romGuideline: "Hold a straight shoulder-hip-ankle line (roughly 160-180°) for the target time.",
      tutTarget: [20, 60],
    },
    def: {
      id: "front-plank",
      name: "Front Plank",
      category: "core",
      dbCategory: "plank",
      dbSlug: "front_plank",
      equipment: ["Bodyweight"],
      mode: "hold",
      view: "side",
      unilateral: false,
      target: { seconds: 40, sets: 2 },
      tempo: "hold",
      camera: "Side view — shoulders, hips, and ankles visible",
      setupCue: "Frame your full side profile before you start.",
      keyJoints: bodyTriplet,
      measure: angleMeasure("shoulder", "hip", "ankle", "best"),
      restAngle: 180,
      activeAngle: 150,
      minRepFraction: 1,
      holdBand: [158, 182],
      holdMeasure: (pose) => {
        const m = angleMeasure("shoulder", "hip", "ankle", "best")(pose);
        return m ? { angle: m.angle, quality: m.quality } : null;
      },
      formChecks: [
        bodyLineCheck(
          "Squeeze your glutes and lift your hips into one line.",
          "Drop your hips down, long and level.",
        ),
      ],
      focus: ["hold_time", "control", "line"],
      reviewCue: "Hold a long, level line and keep the timer honest.",
    },
  },
  // ---------------------------------------------------------------- side plank
  {
    meta: {
      slug: "side_plank",
      name: "Side Plank",
      aliases: ["side plank", "side bridge"],
      primaryMuscles: ["obliques", "core"],
      secondaryMuscles: ["shoulders", "glutes", "abductors"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Lie on your side with your forearm under your shoulder.",
        "Stack your feet and lift your hips off the floor.",
        "Form a straight line from your head through your hips to your feet.",
        "Hold for time, then switch sides.",
      ],
      formPoints: [
        "Keep your hips lifted and stacked in a straight line.",
        "Support yourself with your forearm directly under your shoulder.",
        "Brace your obliques to hold the position.",
        "Keep your neck neutral and breathe steadily.",
      ],
      commonMistakes: [
        "Letting the hips drift down toward the floor.",
        "Rotating the torso forward or back.",
        "Holding your breath through the set.",
      ],
      romGuideline: "Hold a straight head-hip-foot line with hips lifted for the target time.",
      tutTarget: [15, 45],
    },
    def: {
      id: "side-plank",
      name: "Side Plank",
      category: "core",
      dbCategory: "plank",
      dbSlug: "side_plank",
      equipment: ["Bodyweight"],
      mode: "hold",
      view: "front",
      unilateral: true,
      target: { seconds: 30, sets: 2 },
      tempo: "hold",
      camera: "Facing the camera — shoulders, hips, and ankles visible",
      setupCue: "Set up so your full body line faces the camera.",
      keyJoints: bodyTriplet,
      measure: angleMeasure("shoulder", "hip", "ankle", "best"),
      restAngle: 180,
      activeAngle: 150,
      minRepFraction: 1,
      holdBand: [158, 182],
      holdMeasure: (pose) => {
        const m = angleMeasure("shoulder", "hip", "ankle", "best")(pose);
        return m ? { angle: m.angle, quality: m.quality } : null;
      },
      formChecks: [
        bodyLineCheck(
          "Lift your hips into one straight line.",
          "Ease your hips down, long and level.",
        ),
      ],
      focus: ["hold_time", "control", "line"],
      reviewCue: "Keep your hips lifted and hold an even line each side.",
    },
  },
  // ---------------------------------------------------------------- crunch (existing)
  {
    meta: {
      slug: "crunch",
      name: "Crunch",
      aliases: ["crunch", "ab crunch"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["obliques", "hip_flexors"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Lie on your back with knees bent and feet flat on the floor.",
        "Rest your hands lightly by your head or across your chest.",
        "Curl your shoulder blades up off the floor by contracting your abs.",
        "Lower back down under control and repeat.",
      ],
      formPoints: [
        "Curl from the abs and peel your shoulder blades off the floor.",
        "Keep your lower back in contact with the floor.",
        "Move with control rather than yanking on your neck.",
        "Exhale as you crunch up.",
      ],
      commonMistakes: [
        "Pulling on the head and neck to lift up.",
        "Bouncing off the floor instead of controlling each rep.",
        "Barely lifting the shoulders off the ground.",
      ],
      romGuideline: "Shoulder blades lift clear of the floor as the trunk flexes; hip angle closes toward ~70°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "crunch",
      name: "Crunch",
      category: "core",
      dbCategory: "other",
      dbSlug: "crunch",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 15, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view lying down, torso and knees visible",
      setupCue: "Lie side-on to the camera with knees bent.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 125,
      activeAngle: 72,
      minRepFraction: 0.45,
      formChecks: [depthCheck("Peel your shoulder blades off the floor.", 0.45)],
      focus: ["range", "control", "tempo"],
      reviewCue: "Curl up from the chest and lower with control.",
    },
  },
  // ---------------------------------------------------------------- sit-up
  {
    meta: {
      slug: "sit_up",
      name: "Sit-up",
      aliases: ["sit up", "situp", "full sit-up"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["hip_flexors", "obliques"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Lie on your back with knees bent and feet flat.",
        "Cross your arms over your chest or reach toward your knees.",
        "Curl and sit all the way up until your torso is upright.",
        "Lower back down under control and repeat.",
      ],
      formPoints: [
        "Curl up segment by segment rather than jerking off the floor.",
        "Keep your feet planted and your chin tucked slightly.",
        "Come to a tall seated position at the top.",
        "Lower with control instead of dropping back.",
      ],
      commonMistakes: [
        "Yanking the neck to initiate the movement.",
        "Using momentum to swing up.",
        "Only doing a partial range.",
      ],
      romGuideline: "Torso curls from the floor up to about vertical; hip angle closes toward ~55°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "sit-up",
      name: "Sit-up",
      category: "core",
      dbCategory: "other",
      dbSlug: "sit_up",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 15, sets: 3 },
      tempo: "2-0-1-0",
      camera: "Side view lying down, torso and knees visible",
      setupCue: "Lie side-on to the camera with knees bent.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 155,
      activeAngle: 60,
      minRepFraction: 0.6,
      formChecks: [depthCheck("Sit all the way up to a tall torso.", 0.6)],
      focus: ["range", "control", "tempo"],
      reviewCue: "Curl up fully and lower with control.",
    },
  },
  // ---------------------------------------------------------------- lying leg raise
  {
    meta: {
      slug: "lying_leg_raise",
      name: "Lying Leg Raise",
      aliases: ["leg raise", "lying leg raise", "straight leg raise"],
      primaryMuscles: ["core", "hip_flexors"],
      secondaryMuscles: ["quads"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Lie on your back with legs straight and hands by your sides or under your hips.",
        "Keeping your legs fairly straight, raise them toward vertical.",
        "Lift until your hips flex and your feet point up.",
        "Lower under control without letting your feet touch the floor, then repeat.",
      ],
      formPoints: [
        "Keep your lower back pressed into the floor.",
        "Raise your legs with control rather than swinging them.",
        "Lower slowly to keep tension on the abs.",
        "Keep your legs fairly straight throughout.",
      ],
      commonMistakes: [
        "Arching the lower back off the floor.",
        "Using momentum to swing the legs up.",
        "Dropping the legs down quickly.",
      ],
      romGuideline: "Legs raise from the floor toward vertical; hip angle closes toward ~90°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "lying-leg-raise",
      name: "Lying Leg Raise",
      category: "core",
      dbCategory: "other",
      dbSlug: "lying_leg_raise",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view lying down, hips and legs visible",
      setupCue: "Lie side-on to the camera with your legs in frame.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "min"),
      restAngle: 172,
      activeAngle: 95,
      minRepFraction: 0.55,
      formChecks: [depthCheck("Raise your legs toward vertical.", 0.55)],
      focus: ["range", "control", "tempo"],
      reviewCue: "Raise and lower your legs with steady control.",
    },
  },
  // ---------------------------------------------------------------- mountain climber
  {
    meta: {
      slug: "mountain_climber",
      name: "Mountain Climber",
      aliases: ["mountain climber", "mountain climbers"],
      primaryMuscles: ["core", "hip_flexors"],
      secondaryMuscles: ["shoulders", "quads", "obliques"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Start in a high plank with hands under your shoulders.",
        "Drive one knee toward your chest, then switch legs.",
        "Keep alternating knees at a steady pace.",
        "Hold a strong plank line the whole time.",
      ],
      formPoints: [
        "Keep your hips level with your shoulders as you drive your knees.",
        "Drive each knee well forward for a full range.",
        "Keep a steady rhythm rather than bouncing.",
        "Brace your core throughout.",
      ],
      commonMistakes: [
        "Letting the hips pike up high.",
        "Short, choppy knee drives.",
        "Losing the plank line as you speed up.",
      ],
      romGuideline: "Each knee drives from extended toward the chest; hip closes toward ~90°.",
      tutTarget: [1, 2],
    },
    def: {
      id: "mountain-climber",
      name: "Mountain Climber",
      category: "core",
      dbCategory: "other",
      dbSlug: "mountain_climber",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 20, sets: 3 },
      tempo: "quick",
      camera: "Side view — shoulders, hips, and knees visible",
      setupCue: "Set a high plank side-on to the camera.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "min"),
      restAngle: 165,
      activeAngle: 95,
      minRepFraction: 0.5,
      formChecks: [depthCheck("Drive your knee further toward your chest.", 0.5)],
      focus: ["range", "rhythm", "control"],
      reviewCue: "Keep the plank steady and drive each knee fully.",
    },
  },
];
