// HINGE — hip-dominant patterns (deadlift, RDL, hip thrust, swing, bridge).
// Rep driver is the hip angle (shoulder-hip-knee, side view). Glute bridge and
// hip thrust invert (angle grows toward lockout). Angles follow standard hinge
// depth guidance (torso roughly parallel-ish at the bottom of an RDL).

import { depthCheck, hingeKneeCheck, flatBackCheck } from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, hipTriplet } from "./_shared";

export const hinge: ExerciseEntry[] = [
  // ---------------------------------------------------------------- hip hinge / RDL (existing)
  {
    meta: {
      slug: "romanian_deadlift",
      name: "Romanian Deadlift",
      aliases: ["rdl", "romanian deadlift", "hip hinge", "stiff-leg deadlift"],
      primaryMuscles: ["hamstrings", "glutes"],
      secondaryMuscles: ["lower_back", "core", "traps"],
      equipment: ["barbell", "dumbbell", "kettlebell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall holding the weight in front of your thighs.",
        "With soft knees, push your hips back and let the weight travel down your legs.",
        "Keep your back flat and lower until you feel a stretch in your hamstrings.",
        "Drive your hips forward to stand tall and finish with a glute squeeze.",
      ],
      formPoints: [
        "Lead with your hips moving back, not your knees bending.",
        "Keep the weight close to your legs the whole way down.",
        "Hold a flat, braced back rather than rounding.",
        "Lower to a comfortable hamstring stretch, usually around mid-shin.",
      ],
      commonMistakes: [
        "Turning it into a squat by bending the knees too much.",
        "Rounding the back as the weight drifts away.",
        "Overreaching for depth beyond a controlled stretch.",
      ],
      romGuideline: "Hinge until the torso is roughly parallel-ish; hip angle ~90-100° side view.",
      tutTarget: [3, 5],
    },
    def: {
      id: "hip-hinge",
      name: "Hip Hinge / RDL",
      category: "legs",
      dbCategory: "hinge",
      dbSlug: "romanian_deadlift",
      equipment: ["Bodyweight", "Dumbbells", "Kettlebell", "Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "3-1-2-0",
      camera: "Side view from head to feet",
      setupCue: "Turn side-on so your hips and shoulders are visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 172,
      activeAngle: 95,
      minRepFraction: 0.6,
      formChecks: [
        hingeKneeCheck("Push your hips back, not down."),
        depthCheck("Hinge a touch further — feel it in the hamstrings.", 0.6),
      ],
      focus: ["hip_pattern", "tempo", "control"],
      reviewCue: "Keep the hinge smooth and drive the hips to stand tall.",
    },
  },
  // ---------------------------------------------------------------- conventional deadlift
  {
    meta: {
      slug: "deadlift",
      name: "Deadlift",
      aliases: ["conventional deadlift", "deadlift"],
      primaryMuscles: ["glutes", "hamstrings", "lower_back"],
      secondaryMuscles: ["quads", "traps", "core", "lats", "forearms"],
      equipment: ["barbell"],
      difficulty: "advanced",
      tier: 1,
      loadType: "external",
      instructions: [
        "Set your mid-foot under the bar with shins close and feet hip-width.",
        "Hinge down, grip the bar, and set a flat back with your chest up.",
        "Take the slack out, then drive your feet into the floor to stand tall.",
        "Lock out with hips and knees straight, then hinge the bar back down under control.",
      ],
      formPoints: [
        "Keep the bar close to your body through the whole pull.",
        "Brace your core and hold a flat back off the floor.",
        "Push the floor away rather than yanking with your back.",
        "Finish tall, then control the bar back down.",
      ],
      commonMistakes: [
        "Letting the hips shoot up before the bar moves.",
        "Rounding the back under the load.",
        "Letting the bar drift out in front of the shins.",
      ],
      romGuideline: "Bar from floor to a tall standing lockout; hips travel from ~90° to straight.",
      tutTarget: [2, 4],
    },
    def: {
      id: "deadlift",
      name: "Deadlift",
      category: "legs",
      dbCategory: "hinge",
      dbSlug: "deadlift",
      equipment: ["Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 5, sets: 4 },
      tempo: "2-0-2-0",
      camera: "Side view from head to feet with the bar visible",
      setupCue: "Set up side-on so your hips, back, and the bar are visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 172,
      activeAngle: 92,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Reach a full rep — stand all the way tall.", 0.6),
        flatBackCheck("Keep your back flat and braced through the pull.", [25, 78]),
      ],
      focus: ["hip_pattern", "posture", "control"],
      reviewCue: "Keep the bar close and lock out tall each rep.",
    },
  },
  // ---------------------------------------------------------------- good morning
  {
    meta: {
      slug: "good_morning",
      name: "Good Morning",
      aliases: ["good morning", "barbell good morning"],
      primaryMuscles: ["hamstrings", "glutes", "lower_back"],
      secondaryMuscles: ["core", "traps"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Rest a bar across your upper back with feet about hip-width.",
        "With soft knees, push your hips back and hinge your torso forward.",
        "Keep your back flat and lower until you feel your hamstrings load.",
        "Drive your hips forward to return to standing tall.",
      ],
      formPoints: [
        "Lead the movement with your hips traveling back.",
        "Keep a flat, braced back throughout.",
        "Only lower as far as you can keep good position.",
        "Stand up by driving the hips, not by rounding up.",
      ],
      commonMistakes: [
        "Bending mostly at the knees instead of hinging.",
        "Rounding the back at the bottom.",
        "Chasing depth beyond a controlled range.",
      ],
      romGuideline: "Torso hinges toward parallel-ish; hip angle ~95-110° side view.",
      tutTarget: [3, 5],
    },
    def: {
      id: "good-morning",
      name: "Good Morning",
      category: "legs",
      dbCategory: "hinge",
      dbSlug: "good_morning",
      equipment: ["Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "3-1-2-0",
      camera: "Side view from head to feet",
      setupCue: "Turn side-on with the bar on your back and hips visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 172,
      activeAngle: 100,
      minRepFraction: 0.55,
      formChecks: [
        hingeKneeCheck("Push your hips back, not down."),
        flatBackCheck("Keep a flat, braced back as you hinge.", [20, 72]),
      ],
      focus: ["hip_pattern", "posture", "control"],
      reviewCue: "Keep the hinge smooth and your back flat.",
    },
  },
  // ---------------------------------------------------------------- hip thrust
  {
    meta: {
      slug: "hip_thrust",
      name: "Barbell Hip Thrust",
      aliases: ["hip thrust", "barbell hip thrust"],
      primaryMuscles: ["glutes"],
      secondaryMuscles: ["hamstrings", "quads", "core"],
      equipment: ["barbell", "bench"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Sit on the floor with your upper back against a bench and the bar over your hips.",
        "Plant your feet flat, roughly under your knees when bridged.",
        "Drive through your heels to lift your hips until your body is level.",
        "Squeeze your glutes at the top, then lower under control.",
      ],
      formPoints: [
        "Finish with your hips fully extended to a flat torso.",
        "Keep your chin tucked and ribs down at the top.",
        "Drive through your heels rather than your toes.",
        "Control the lowering rather than dropping the hips.",
      ],
      commonMistakes: [
        "Stopping short of full hip extension.",
        "Overarching the lower back at the top.",
        "Feet set too far forward or back.",
      ],
      romGuideline: "Hips travel from a lowered position to a level, fully extended top.",
      tutTarget: [2, 4],
    },
    def: {
      id: "hip-thrust",
      name: "Hip Thrust",
      category: "legs",
      dbCategory: "hinge",
      dbSlug: "hip_thrust",
      equipment: ["Barbell", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "1-1-2-1",
      camera: "Side view, hips and knees visible with the bench behind you",
      setupCue: "Set up side-on with your back on the bench and hips in frame.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 100,
      activeAngle: 172,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Drive the hips all the way up to level.", 0.7),
      ],
      focus: ["range", "control", "lockout"],
      reviewCue: "Reach full hip extension and pause at the top.",
    },
  },
  // ---------------------------------------------------------------- glute bridge (existing)
  {
    meta: {
      slug: "glute_bridge",
      name: "Glute Bridge",
      aliases: ["glute bridge", "floor bridge"],
      primaryMuscles: ["glutes"],
      secondaryMuscles: ["hamstrings", "core"],
      equipment: ["bodyweight", "dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "both",
      instructions: [
        "Lie on your back with knees bent and feet flat, hip-width apart.",
        "Push through your heels to lift your hips toward a straight line.",
        "Squeeze your glutes at the top with your ribs down.",
        "Lower your hips under control and repeat.",
      ],
      formPoints: [
        "Reach a straight line from shoulders to knees at the top.",
        "Drive through your heels and squeeze your glutes.",
        "Keep your ribs down instead of arching your lower back.",
        "Control the lowering phase each rep.",
      ],
      commonMistakes: [
        "Stopping short of full hip extension.",
        "Overarching the lower back at the top.",
        "Pushing through the toes instead of the heels.",
      ],
      romGuideline: "Hips rise to a straight shoulder-hip-knee line at the top.",
      tutTarget: [2, 4],
    },
    def: {
      id: "glute-bridge",
      name: "Glute Bridge",
      category: "legs",
      dbCategory: "other",
      dbSlug: "glute_bridge",
      equipment: ["Bodyweight", "Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-1-1",
      camera: "Side view lying down, hips and knees visible",
      setupCue: "Lie side-on to the camera with knees bent.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 120,
      activeAngle: 173,
      minRepFraction: 0.7,
      formChecks: [depthCheck("Squeeze all the way up to a straight line.", 0.7)],
      focus: ["range", "control", "tempo"],
      reviewCue: "Drive the hips fully up and pause at the top.",
    },
  },
  // ---------------------------------------------------------------- kettlebell swing
  {
    meta: {
      slug: "kettlebell_swing",
      name: "Kettlebell Swing",
      aliases: ["kb swing", "kettlebell swing", "russian swing"],
      primaryMuscles: ["glutes", "hamstrings"],
      secondaryMuscles: ["core", "lower_back", "shoulders", "lats"],
      equipment: ["kettlebell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand with feet about shoulder-width and the kettlebell a step in front.",
        "Hinge to grip the bell, then hike it back between your legs.",
        "Snap your hips forward to float the bell up to about chest height.",
        "Let it swing back down as you hinge, and flow into the next rep.",
      ],
      formPoints: [
        "Power the swing with a sharp hip snap, not your arms.",
        "Keep a flat, braced back on every hinge.",
        "Let the bell float — your hips do the work.",
        "Stand fully tall at the top of each swing.",
      ],
      commonMistakes: [
        "Squatting the swing instead of hinging.",
        "Lifting the bell with the arms and shoulders.",
        "Rounding the back at the bottom.",
      ],
      romGuideline: "Hips hinge to ~90-100° and snap to a tall, fully extended finish.",
      tutTarget: [1, 2],
    },
    def: {
      id: "kettlebell-swing",
      name: "Kettlebell Swing",
      category: "legs",
      dbCategory: "hinge",
      dbSlug: "kettlebell_swing",
      equipment: ["Kettlebell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 15, sets: 3 },
      tempo: "explosive",
      camera: "Side view from head to feet with room for the swing",
      setupCue: "Turn side-on with the kettlebell and your hips visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 172,
      activeAngle: 108,
      minRepFraction: 0.5,
      formChecks: [
        hingeKneeCheck("Hinge the hips back — don't squat the swing."),
      ],
      focus: ["hip_pattern", "power", "rhythm"],
      reviewCue: "Snap the hips and stand tall on every swing.",
    },
  },
];
