// LEGS — squat and lunge family (quad/glute dominant knee-bend patterns).
// Tier 1 movements: full MovementDef + form checks, side/front camera views.
// Angles follow mainstream strength-coaching depth standards (side view:
// thighs-to-parallel ≈ knee angle ~85-100°), widened slightly for camera noise.

import {
  depthCheck,
  kneeValgusCheck,
  torsoLeanCheck,
} from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, kneeTriplet } from "./_shared";

export const legs: ExerciseEntry[] = [
  // ---------------------------------------------------------------- squat (existing)
  {
    meta: {
      slug: "squat",
      name: "Squat",
      aliases: ["air squat", "bodyweight squat", "back squat", "squat"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core", "adductors"],
      equipment: ["bodyweight", "dumbbell", "barbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand with feet about shoulder-width apart, toes turned slightly out.",
        "Brace your core and keep your chest up as you sit your hips back and down.",
        "Lower until your thighs reach about parallel, keeping your heels planted.",
        "Drive through the whole foot to stand back up to a tall finish.",
      ],
      formPoints: [
        "Track your knees out over your toes rather than letting them collapse inward.",
        "Aim for thighs about parallel to the floor on each rep for a consistent range.",
        "Keep your torso proud and your weight balanced over the middle of your foot.",
        "Control the way down, then drive up with intent.",
      ],
      commonMistakes: [
        "Cutting depth short and bouncing at the top.",
        "Letting the knees cave inward under load.",
        "Rounding forward and losing the tall chest position.",
      ],
      romGuideline: "Hips crease to about knee height; knee bends to roughly 85-95° side view.",
      tutTarget: [3, 5],
    },
    def: {
      id: "squat",
      name: "Squat",
      category: "legs",
      dbCategory: "squat",
      dbSlug: "squat",
      equipment: ["Bodyweight", "Dumbbells", "Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "3-1-1-0",
      camera: "Side or front view, full body from head to feet",
      setupCue: "Stand tall in frame with your whole body visible.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 172,
      activeAngle: 92,
      minRepFraction: 0.72,
      formChecks: [
        depthCheck("Sit a little deeper — aim for thighs parallel.", 0.72),
        kneeValgusCheck("Push your knees out over your toes."),
        torsoLeanCheck("Chest up and proud.", 58),
      ],
      focus: ["depth", "tempo", "control"],
      reviewCue: "Keep the descent controlled and hit the same depth each rep.",
    },
  },
  // ---------------------------------------------------------------- goblet squat
  {
    meta: {
      slug: "goblet_squat",
      name: "Goblet Squat",
      aliases: ["goblet squat", "kb goblet squat"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["core", "adductors", "hamstrings"],
      equipment: ["dumbbell", "kettlebell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Hold a dumbbell or kettlebell against your chest with both hands.",
        "Set your feet a little wider than shoulder-width, toes slightly out.",
        "Sit down between your hips, keeping the weight close and your chest tall.",
        "Reach about parallel, then stand up and squeeze your glutes at the top.",
      ],
      formPoints: [
        "Keep the weight tight to your chest so your torso stays upright.",
        "Let your elbows travel down between your knees at the bottom.",
        "Track your knees out in line with your toes.",
        "Own a consistent depth on every rep.",
      ],
      commonMistakes: [
        "Letting the weight drift away from the body.",
        "Heels lifting off the floor at depth.",
        "Rushing the bottom instead of controlling it.",
      ],
      romGuideline: "Thighs to about parallel; knee bends to roughly 85-95° side view.",
      tutTarget: [3, 5],
    },
    def: {
      id: "goblet-squat",
      name: "Goblet Squat",
      category: "legs",
      dbCategory: "squat",
      dbSlug: "goblet_squat",
      equipment: ["Dumbbell", "Kettlebell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "3-1-1-0",
      camera: "Side or front view, full body from head to feet",
      setupCue: "Hold the weight at your chest and frame your whole body.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 172,
      activeAngle: 90,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Sit a little deeper — thighs toward parallel.", 0.7),
        kneeValgusCheck("Drive your knees out as you stand."),
        torsoLeanCheck("Stay tall — keep the weight on your chest.", 50),
      ],
      focus: ["depth", "posture", "control"],
      reviewCue: "Keep the torso tall and match your depth each rep.",
    },
  },
  // ---------------------------------------------------------------- front squat
  {
    meta: {
      slug: "front_squat",
      name: "Front Squat",
      aliases: ["front squat", "barbell front squat"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["core", "traps", "lower_back"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Rack the bar across the front of your shoulders with high elbows.",
        "Set your feet about shoulder-width, toes slightly turned out.",
        "Brace and squat straight down, keeping your elbows and chest up.",
        "Reach about parallel, then drive up to a tall lockout.",
      ],
      formPoints: [
        "Keep your elbows high so the bar stays supported on your shoulders.",
        "Sit straight down with an upright torso rather than hinging forward.",
        "Track your knees out over your toes through the full rep.",
        "Match the same depth on every rep.",
      ],
      commonMistakes: [
        "Elbows dropping and the chest folding forward.",
        "Heels rising as the torso pitches over.",
        "Cutting depth short under heavier loads.",
      ],
      romGuideline: "Thighs to about parallel with an upright torso; knee ~85-95° side view.",
      tutTarget: [3, 5],
    },
    def: {
      id: "front-squat",
      name: "Front Squat",
      category: "legs",
      dbCategory: "squat",
      dbSlug: "front_squat",
      equipment: ["Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 6, sets: 4 },
      tempo: "3-1-1-0",
      camera: "Side view, full body from head to feet",
      setupCue: "Rack the bar on your shoulders and frame your whole body.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 172,
      activeAngle: 90,
      minRepFraction: 0.7,
      formChecks: [
        depthCheck("Sit a touch deeper — thighs to parallel.", 0.7),
        torsoLeanCheck("Elbows up, chest tall.", 40),
      ],
      focus: ["depth", "posture", "control"],
      reviewCue: "Keep the torso upright and hold your depth each rep.",
    },
  },
  // ---------------------------------------------------------------- split squat
  {
    meta: {
      slug: "split_squat",
      name: "Split Squat",
      aliases: ["static lunge", "split squat"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core", "adductors"],
      equipment: ["bodyweight", "dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "both",
      instructions: [
        "Set up in a staggered stance, one foot forward and one back.",
        "Keep most of your weight through the front foot.",
        "Lower straight down until your front thigh is about parallel.",
        "Drive through the front foot to return to the start, then swap sides.",
      ],
      formPoints: [
        "Drop straight down rather than drifting your front knee far forward.",
        "Keep your torso tall and stacked over your hips.",
        "Use a full, matched range on both legs.",
        "Control the descent and stay balanced.",
      ],
      commonMistakes: [
        "Leaning the torso forward onto the front thigh.",
        "Short, shallow reps that skip the bottom.",
        "Wobbling instead of owning a stable stance.",
      ],
      romGuideline: "Front thigh to about parallel; front knee ~90° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "split-squat",
      name: "Split Squat",
      category: "legs",
      dbCategory: "lunge",
      dbSlug: "split_squat",
      equipment: ["Bodyweight", "Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, full body visible",
      setupCue: "Set a staggered stance side-on to the camera.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 170,
      activeAngle: 92,
      minRepFraction: 0.62,
      formChecks: [
        depthCheck("Sink lower — front thigh toward parallel.", 0.62),
        torsoLeanCheck("Stay tall through your chest.", 34),
      ],
      focus: ["depth", "balance", "control"],
      reviewCue: "Match your range on both legs and finish tall.",
    },
  },
  // ---------------------------------------------------------------- bulgarian split squat
  {
    meta: {
      slug: "bulgarian_split_squat",
      name: "Bulgarian Split Squat",
      aliases: ["rear foot elevated split squat", "bulgarian split squat", "rfess"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core", "adductors"],
      equipment: ["bodyweight", "dumbbell", "bench"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand a stride's length in front of a bench and rest your rear foot on it.",
        "Keep most of your weight through the planted front foot.",
        "Lower straight down until your front thigh is about parallel.",
        "Drive up through the front foot, then finish your reps and switch sides.",
      ],
      formPoints: [
        "Keep your front shin fairly vertical and lower straight down.",
        "Stay tall through the torso with your hips square.",
        "Own a full range and the same depth each rep.",
        "Let the rear leg assist balance, not drive the rep.",
      ],
      commonMistakes: [
        "Pushing the front knee far past the toes.",
        "Turning it into a shallow bounce.",
        "Twisting the hips out of square.",
      ],
      romGuideline: "Front thigh to about parallel; front knee ~90° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "bulgarian-split-squat",
      name: "Bulgarian Split Squat",
      category: "legs",
      dbCategory: "lunge",
      dbSlug: "bulgarian_split_squat",
      equipment: ["Bodyweight", "Dumbbells", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 8, sets: 3 },
      tempo: "3-1-1-0",
      camera: "Side view, full body and the bench visible",
      setupCue: "Rest your rear foot on the bench, side-on to the camera.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 168,
      activeAngle: 92,
      minRepFraction: 0.62,
      formChecks: [
        depthCheck("Lower further — front thigh toward parallel.", 0.62),
        torsoLeanCheck("Keep your chest tall over the front foot.", 40),
      ],
      focus: ["depth", "balance", "control"],
      reviewCue: "Stay balanced and match your depth on both legs.",
    },
  },
  // ---------------------------------------------------------------- reverse lunge (existing)
  {
    meta: {
      slug: "reverse_lunge",
      name: "Reverse Lunge",
      aliases: ["reverse lunge", "backward lunge"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core", "adductors"],
      equipment: ["bodyweight", "dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand tall with feet hip-width apart.",
        "Step one foot back and lower into a lunge until your front thigh is about parallel.",
        "Keep your torso upright and your front knee tracking over your foot.",
        "Drive through the front foot to return to standing, then alternate.",
      ],
      formPoints: [
        "Step back far enough that both knees bend to about 90°.",
        "Keep your weight in the front heel and stay tall.",
        "Lower with control rather than dropping the back knee.",
        "Use the same range on each side.",
      ],
      commonMistakes: [
        "Short steps that jam the front knee forward.",
        "Leaning the torso far over the front leg.",
        "Rushing the reps and losing balance.",
      ],
      romGuideline: "Front thigh to about parallel; front knee ~90° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "reverse-lunge",
      name: "Reverse Lunge",
      category: "legs",
      dbCategory: "lunge",
      dbSlug: "reverse_lunge",
      equipment: ["Bodyweight", "Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view with room behind you, full body visible",
      setupCue: "Step into frame with room to lunge backward.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 170,
      activeAngle: 92,
      minRepFraction: 0.62,
      formChecks: [
        depthCheck("Sink a little lower — front thigh toward parallel.", 0.62),
        torsoLeanCheck("Stay tall through your chest.", 34),
      ],
      focus: ["depth", "balance", "control"],
      reviewCue: "Use the same range on each side and finish tall.",
    },
  },
  // ---------------------------------------------------------------- forward lunge
  {
    meta: {
      slug: "forward_lunge",
      name: "Forward Lunge",
      aliases: ["forward lunge", "lunge"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core", "adductors"],
      equipment: ["bodyweight", "dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand tall with feet hip-width apart.",
        "Step one foot forward and lower until your front thigh is about parallel.",
        "Keep your torso upright and your front knee over your foot.",
        "Push back to standing, then alternate legs.",
      ],
      formPoints: [
        "Take a full stride so both knees bend to about 90°.",
        "Keep your chest tall and your weight balanced.",
        "Push back off the front foot with control.",
        "Match your range side to side.",
      ],
      commonMistakes: [
        "Letting the front knee drift far past the toes.",
        "Falling forward instead of stepping under control.",
        "Shallow, rushed reps.",
      ],
      romGuideline: "Front thigh to about parallel; front knee ~90° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "forward-lunge",
      name: "Forward Lunge",
      category: "legs",
      dbCategory: "lunge",
      dbSlug: "forward_lunge",
      equipment: ["Bodyweight", "Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view with room in front, full body visible",
      setupCue: "Step into frame with room to lunge forward.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 170,
      activeAngle: 92,
      minRepFraction: 0.62,
      formChecks: [
        depthCheck("Step longer and sink to parallel.", 0.62),
        torsoLeanCheck("Stay tall through your chest.", 36),
      ],
      focus: ["depth", "balance", "control"],
      reviewCue: "Control the step and match your depth each side.",
    },
  },
  // ---------------------------------------------------------------- walking lunge
  {
    meta: {
      slug: "walking_lunge",
      name: "Walking Lunge",
      aliases: ["walking lunge", "alternating lunge"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings", "core", "adductors", "calves"],
      equipment: ["bodyweight", "dumbbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand tall with space ahead of you to move forward.",
        "Step one foot forward into a lunge until the front thigh is about parallel.",
        "Drive up and forward, bringing the back foot through into the next lunge.",
        "Continue walking forward, alternating legs each step.",
      ],
      formPoints: [
        "Take even, full-length strides so each knee bends to about 90°.",
        "Stay tall and keep each step balanced before pushing off.",
        "Track your front knee over your foot.",
        "Keep a steady rhythm rather than rushing.",
      ],
      commonMistakes: [
        "Short strides that push the knee forward.",
        "Losing balance between steps.",
        "Uneven depth from side to side.",
      ],
      romGuideline: "Front thigh to about parallel; front knee ~90° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "walking-lunge",
      name: "Walking Lunge",
      category: "legs",
      dbCategory: "lunge",
      dbSlug: "walking_lunge",
      equipment: ["Bodyweight", "Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-0-1-0",
      camera: "Side view with room to move, full body visible",
      setupCue: "Face side-on with space to walk forward.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 170,
      activeAngle: 94,
      minRepFraction: 0.58,
      formChecks: [
        depthCheck("Take a full stride and sink to parallel.", 0.58),
        torsoLeanCheck("Stay tall as you step through.", 38),
      ],
      focus: ["depth", "balance", "rhythm"],
      reviewCue: "Keep your strides even and your torso tall.",
    },
  },
  // ---------------------------------------------------------------- lateral lunge
  {
    meta: {
      slug: "lateral_lunge",
      name: "Lateral Lunge",
      aliases: ["side lunge", "lateral lunge"],
      primaryMuscles: ["quads", "glutes", "adductors"],
      secondaryMuscles: ["hamstrings", "core", "abductors"],
      equipment: ["bodyweight", "dumbbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand tall with feet together and room to step out to the side.",
        "Take a wide step sideways and sit back into that hip.",
        "Keep the trailing leg fairly straight and your chest up.",
        "Push back to the middle, then work the other side.",
      ],
      formPoints: [
        "Sit back into the bent-leg hip rather than pushing the knee forward.",
        "Keep both feet flat and pointing forward.",
        "Stay tall through the chest as you load the side.",
        "Match the depth and range on both legs.",
      ],
      commonMistakes: [
        "Short steps with little hip loading.",
        "Rounding forward over the working leg.",
        "Letting the working knee cave inward.",
      ],
      romGuideline: "Bent knee to roughly 90-110° as you sit into the hip (side/front view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "lateral-lunge",
      name: "Lateral Lunge",
      category: "legs",
      dbCategory: "lunge",
      dbSlug: "lateral_lunge",
      equipment: ["Bodyweight", "Dumbbells"],
      mode: "rep",
      view: "front",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Front view with room to step sideways, full body visible",
      setupCue: "Face the camera with room to step out to the side.",
      keyJoints: kneeTriplet,
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 172,
      activeAngle: 108,
      minRepFraction: 0.55,
      formChecks: [
        depthCheck("Sit deeper into the working hip.", 0.55),
      ],
      focus: ["range", "balance", "control"],
      reviewCue: "Load the hip and match your range on both sides.",
    },
  },
  // ---------------------------------------------------------------- calf raise
  {
    meta: {
      slug: "standing_calf_raise",
      name: "Standing Calf Raise",
      aliases: ["calf raise", "standing calf raise", "heel raise"],
      primaryMuscles: ["calves"],
      secondaryMuscles: [],
      equipment: ["bodyweight", "dumbbell", "machine"],
      difficulty: "beginner",
      tier: 1,
      loadType: "both",
      instructions: [
        "Stand tall with the balls of your feet on the floor or a small step.",
        "Push through the balls of your feet to lift your heels as high as you can.",
        "Pause briefly at the top with a strong calf squeeze.",
        "Lower your heels under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Rise up onto the balls of your feet through a full range each rep.",
        "Pause at the top rather than bouncing.",
        "Lower slowly to feel a stretch at the bottom.",
        "Keep your knees mostly straight so the calves do the work.",
      ],
      commonMistakes: [
        "Short, bouncy reps with little range.",
        "Rushing the lowering phase.",
        "Bending the knees to cheat the movement.",
      ],
      romGuideline: "Full heel lift at the top to a controlled stretch at the bottom (side view ankle range).",
      tutTarget: [2, 4],
    },
    def: {
      id: "calf-raise",
      name: "Standing Calf Raise",
      category: "legs",
      dbCategory: "other",
      dbSlug: "standing_calf_raise",
      equipment: ["Bodyweight", "Dumbbells", "Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 15, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Side view, ankles and feet clearly visible",
      setupCue: "Stand side-on with your feet clearly in frame.",
      keyJoints: ["knee", "ankle", "foot"],
      measure: angleMeasure("knee", "ankle", "foot", "max"),
      restAngle: 110,
      activeAngle: 148,
      minRepFraction: 0.55,
      formChecks: [
        depthCheck("Push higher onto the balls of your feet.", 0.55),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Rise up fully and lower with control each rep.",
    },
  },
];
