// MACHINES & CABLES — tier 2 movements (guided-path resistance work).
//
// A single, dominant joint angle drives reliable rep counting on these machine
// and cable exercises: the fixed load path means the tracked joint sweeps a
// clean, repeatable arc the engine can segment into reps. What we deliberately
// DON'T do here is judge form. On a leg press, pec deck, or lat pulldown the
// meaningful form cues (spinal position against a pad, scapular control, seat
// setup, out-of-plane drift) live along axes a single camera can't see
// honestly — inferring them would be fake precision. So every def below counts
// reps and estimates range of motion, but ships `formChecks: []`. That keeps
// the coaching we surface truthful: we count what we can measure and stay quiet
// about what we can't.

import type { ExerciseEntry } from "../types";
import { angleMeasure, elbowTriplet, hipTriplet } from "./_shared";

export const machines: ExerciseEntry[] = [
  // ---------------------------------------------------------------- lat pulldown
  {
    meta: {
      slug: "lat_pulldown",
      name: "Lat Pulldown",
      aliases: ["lat pulldown", "pulldown", "wide grip pulldown"],
      primaryMuscles: ["lats", "back"],
      secondaryMuscles: ["biceps"],
      equipment: ["cable", "machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the thigh pad and grab the bar a little wider than shoulder-width.",
        "Sit tall with your chest up and a slight lean back through your torso.",
        "Pull the bar down toward the top of your chest, leading with your elbows.",
        "Let the bar rise back up under control until your arms are long again.",
      ],
      formPoints: [
        "Drive your elbows down and back rather than just bending them.",
        "Keep your chest tall and avoid swinging your torso for momentum.",
        "Pull to roughly upper-chest height for a full, repeatable range.",
        "Control the bar back up instead of letting it snap your arms straight.",
      ],
      commonMistakes: [
        "Heaving with the whole body to move heavier weight.",
        "Stopping short and only doing half the range.",
        "Letting the bar yank the arms straight on the way up.",
      ],
      romGuideline: "Arms long at the top down to the bar near the chest; elbow flexes to roughly 60°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "lat-pulldown",
      name: "Lat Pulldown",
      category: "pull",
      dbCategory: "other",
      dbSlug: "lat_pulldown",
      equipment: ["Cable", "Machine"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, upper body and the bar clearly in frame",
      setupCue: "Sit facing the camera with your torso and arms in view.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 168,
      activeAngle: 60,
      minRepFraction: 0.6,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Pull to the same height each rep and control the bar back up.",
    },
  },
  // ---------------------------------------------------------------- seated cable row
  {
    meta: {
      slug: "seated_cable_row",
      name: "Seated Cable Row",
      aliases: ["seated row", "cable row", "seated cable row"],
      primaryMuscles: ["back", "lats"],
      secondaryMuscles: ["biceps"],
      equipment: ["cable", "machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Sit with your feet braced and a slight bend in your knees.",
        "Grab the handle and sit tall with your arms extended in front.",
        "Pull the handle to your midsection, driving your elbows back.",
        "Let the handle travel forward under control until your arms are long.",
      ],
      formPoints: [
        "Lead with your elbows and draw them past your torso.",
        "Keep your chest up and your torso fairly still through the pull.",
        "Pull to about your belly for a full, consistent range.",
        "Control the return rather than letting the stack pull you forward.",
      ],
      commonMistakes: [
        "Rocking the torso back and forth for momentum.",
        "Shrugging the shoulders up toward the ears.",
        "Cutting the range short at either end.",
      ],
      romGuideline: "Arms extended to the handle at the torso; elbow flexes to roughly 75°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "seated-cable-row",
      name: "Seated Cable Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "seated_cable_row",
      equipment: ["Cable", "Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, torso and arms clearly in frame",
      setupCue: "Sit side-on to the camera with your arms in view.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 75,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Pull to the same point each rep and control the return.",
    },
  },
  // ---------------------------------------------------------------- chest fly
  {
    meta: {
      slug: "chest_fly",
      name: "Chest Fly",
      aliases: ["dumbbell fly", "chest fly", "flye"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["shoulders"],
      equipment: ["dumbbell", "cable", "machine", "bench"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Lie back on a bench holding a weight in each hand over your chest.",
        "Keep a soft, fixed bend in your elbows throughout.",
        "Open your arms out to the sides in a wide arc until you feel a stretch.",
        "Bring your hands back together over your chest under control.",
      ],
      formPoints: [
        "Move at the shoulders in a smooth arc, keeping the elbow angle fixed.",
        "Open only as far as you can control comfortably.",
        "Squeeze your chest as your hands come together at the top.",
        "Keep the same arc on every rep for a consistent range.",
      ],
      commonMistakes: [
        "Turning it into a press by bending and straightening the elbows.",
        "Dropping the arms too far and losing control.",
        "Rushing the reps instead of controlling the arc.",
      ],
      romGuideline: "Arms wide at the stretch in to hands together; measured angle closes to roughly 20°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "chest-fly",
      name: "Chest Fly",
      category: "push",
      dbCategory: "other",
      dbSlug: "chest_fly",
      equipment: ["Dumbbells", "Cable", "Machine", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, chest and arms clearly in frame",
      setupCue: "Set the bench side-on so your arms are visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("hip", "shoulder", "elbow", "best"),
      restAngle: 90,
      activeAngle: 20,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Keep the same arc and control the weights together and apart.",
    },
  },
  // ---------------------------------------------------------------- cable chest fly
  {
    meta: {
      slug: "cable_chest_fly",
      name: "Cable Chest Fly",
      aliases: ["cable fly", "cable crossover", "cable chest fly"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["shoulders"],
      equipment: ["cable"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the pulleys and grab a handle in each hand, one foot staggered forward.",
        "Start with your arms open wide and a soft, fixed bend in your elbows.",
        "Bring your hands together in front of your chest in a smooth arc.",
        "Let your arms open back out under control to the starting stretch.",
      ],
      formPoints: [
        "Sweep your arms in an arc, keeping the elbow angle steady.",
        "Bring your hands together and squeeze your chest at the front.",
        "Stay tall and stable rather than lunging into the movement.",
        "Match the same range on each rep.",
      ],
      commonMistakes: [
        "Bending the elbows to press instead of flying.",
        "Letting the handles yank the arms back too far.",
        "Using the whole body to fling the handles together.",
      ],
      romGuideline: "Arms wide in to hands together in front; measured angle closes to roughly 20°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "cable-chest-fly",
      name: "Cable Chest Fly",
      category: "push",
      dbCategory: "other",
      dbSlug: "cable_chest_fly",
      equipment: ["Cable"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, chest and both arms in frame",
      setupCue: "Face the camera with both arms visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("hip", "shoulder", "elbow", "best"),
      restAngle: 80,
      activeAngle: 20,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Bring your hands to the same point and control the arc back.",
    },
  },
  // ---------------------------------------------------------------- pec deck
  {
    meta: {
      slug: "pec_deck",
      name: "Pec Deck",
      aliases: ["pec deck", "machine fly", "butterfly machine"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["shoulders"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the seat so the handles sit at about chest height.",
        "Sit back with your forearms or hands against the pads.",
        "Bring the pads together in front of your chest in a smooth arc.",
        "Let the pads travel back out under control to a comfortable stretch.",
      ],
      formPoints: [
        "Keep your back against the pad and drive with your chest.",
        "Bring the pads fully together and pause briefly at the front.",
        "Open only as far as you can control comfortably.",
        "Use the same range on every rep.",
      ],
      commonMistakes: [
        "Letting the stack pull the arms back too far and fast.",
        "Shrugging the shoulders up toward the ears.",
        "Short reps that never bring the pads together.",
      ],
      romGuideline: "Pads open at the stretch in to together at the front; measured angle closes to roughly 25°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "pec-deck",
      name: "Pec Deck",
      category: "push",
      dbCategory: "other",
      dbSlug: "pec_deck",
      equipment: ["Machine"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, chest and both arms in frame",
      setupCue: "Face the camera with your arms on the pads and in view.",
      keyJoints: hipTriplet,
      measure: angleMeasure("hip", "shoulder", "elbow", "best"),
      restAngle: 85,
      activeAngle: 25,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Bring the pads fully together and control them back out.",
    },
  },
  // ---------------------------------------------------------------- leg press
  {
    meta: {
      slug: "leg_press",
      name: "Leg Press",
      aliases: ["leg press", "machine leg press"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set your feet about shoulder-width on the platform and release the safeties.",
        "Keep your back and hips settled against the pad.",
        "Bend your knees to lower the platform under control toward you.",
        "Press back up through your whole foot until your legs are nearly long.",
      ],
      formPoints: [
        "Lower to a range where your hips stay settled on the pad.",
        "Push through your whole foot rather than just your toes.",
        "Track your knees in line with your feet.",
        "Stop just short of fully locking the knees at the top.",
      ],
      commonMistakes: [
        "Bouncing the platform at the bottom.",
        "Letting the hips round up off the pad on deep reps.",
        "Slamming the knees straight and locked at the top.",
      ],
      romGuideline: "Legs near-extended at the top down to a controlled bend; knee to roughly 95°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "leg-press",
      name: "Leg Press",
      category: "legs",
      dbCategory: "other",
      dbSlug: "leg_press",
      equipment: ["Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, hips knees and feet in frame",
      setupCue: "Set the machine side-on so your legs are visible.",
      keyJoints: ["hip", "knee", "ankle"],
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 168,
      activeAngle: 95,
      minRepFraction: 0.6,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Hit the same depth each rep and press up under control.",
    },
  },
  // ---------------------------------------------------------------- hack squat
  {
    meta: {
      slug: "hack_squat",
      name: "Hack Squat",
      aliases: ["hack squat", "machine hack squat"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: [],
      equipment: ["machine"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set your shoulders under the pads and your feet on the platform.",
        "Release the safeties and brace with your back against the pad.",
        "Bend your knees to lower under control until your thighs are about parallel.",
        "Drive through your whole foot to press back up to a tall finish.",
      ],
      formPoints: [
        "Keep your back flat against the pad throughout.",
        "Lower until your thighs reach about parallel for a full range.",
        "Track your knees out in line with your feet.",
        "Drive up through your whole foot with control.",
      ],
      commonMistakes: [
        "Cutting depth short and only doing partial reps.",
        "Letting the knees cave inward under load.",
        "Coming off the pad at the bottom.",
      ],
      romGuideline: "Thighs to about parallel; knee to roughly 95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "hack-squat",
      name: "Hack Squat",
      category: "legs",
      dbCategory: "other",
      dbSlug: "hack_squat",
      equipment: ["Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "3-1-1-0",
      camera: "Side view, hips knees and feet in frame",
      setupCue: "Set the machine side-on so your legs are visible.",
      keyJoints: ["hip", "knee", "ankle"],
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 170,
      activeAngle: 95,
      minRepFraction: 0.62,
      formChecks: [],
      focus: ["depth", "control", "tempo"],
      reviewCue: "Match your depth each rep and drive up with control.",
    },
  },
  // ---------------------------------------------------------------- seated shoulder press machine
  {
    meta: {
      slug: "seated_shoulder_press_machine",
      name: "Seated Shoulder Press Machine",
      aliases: ["shoulder press machine", "machine shoulder press", "seated press machine"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["triceps"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the seat so the handles start at about shoulder height.",
        "Sit tall with your back against the pad and grab the handles.",
        "Press the handles up overhead until your arms are nearly long.",
        "Lower the handles back to shoulder height under control.",
      ],
      formPoints: [
        "Press up smoothly and stop just short of locking the elbows.",
        "Keep your back settled against the pad.",
        "Lower to about shoulder height for a full, repeatable range.",
        "Control the descent rather than dropping the handles.",
      ],
      commonMistakes: [
        "Only pressing partway and skipping the top.",
        "Arching the back to push heavier weight.",
        "Letting the handles drop fast on the way down.",
      ],
      romGuideline: "Handles at shoulder height up to near-extended arms; elbow opens to roughly 170°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "seated-shoulder-press-machine",
      name: "Seated Shoulder Press Machine",
      category: "push",
      dbCategory: "other",
      dbSlug: "seated_shoulder_press_machine",
      equipment: ["Machine"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, shoulders and arms in frame",
      setupCue: "Face the camera with your arms and the handles in view.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 80,
      activeAngle: 170,
      minRepFraction: 0.75,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Press to the same height each rep and lower with control.",
    },
  },
  // ---------------------------------------------------------------- chest press machine
  {
    meta: {
      slug: "chest_press_machine",
      name: "Chest Press Machine",
      aliases: ["chest press machine", "machine chest press", "seated chest press"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the seat so the handles line up with about the middle of your chest.",
        "Sit back against the pad and grab the handles.",
        "Press the handles forward until your arms are nearly long.",
        "Let the handles return toward your chest under control.",
      ],
      formPoints: [
        "Press smoothly and stop just short of locking the elbows.",
        "Keep your back and shoulders settled against the pad.",
        "Let the handles return to about chest level for a full range.",
        "Control the return rather than letting it snap back.",
      ],
      commonMistakes: [
        "Pressing only partway out.",
        "Flaring the shoulders forward off the pad.",
        "Letting the stack pull the handles back too fast.",
      ],
      romGuideline: "Handles at the chest out to near-extended arms; elbow opens to roughly 168°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "chest-press-machine",
      name: "Chest Press Machine",
      category: "push",
      dbCategory: "other",
      dbSlug: "chest_press_machine",
      equipment: ["Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, chest and arms in frame",
      setupCue: "Set the machine side-on so your arms are visible.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 90,
      activeAngle: 168,
      minRepFraction: 0.7,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Press to the same point each rep and control the return.",
    },
  },
  // ---------------------------------------------------------------- assisted pull up machine
  {
    meta: {
      slug: "assisted_pull_up_machine",
      name: "Assisted Pull-Up Machine",
      aliases: ["assisted pull up", "assisted pull-up machine", "gravitron"],
      primaryMuscles: ["lats", "back"],
      secondaryMuscles: ["biceps"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "both",
      instructions: [
        "Set the assistance weight and kneel or stand on the platform.",
        "Grab the handles a little wider than shoulder-width.",
        "Pull yourself up until your chin approaches the handles.",
        "Lower yourself back down under control until your arms are long.",
      ],
      formPoints: [
        "Drive your elbows down and back as you pull.",
        "Keep your body fairly still rather than swinging.",
        "Pull to about chin height for a full, repeatable range.",
        "Lower yourself with control instead of dropping.",
      ],
      commonMistakes: [
        "Swinging or kicking to gain momentum.",
        "Stopping short of a full pull.",
        "Dropping quickly on the way down.",
      ],
      romGuideline: "Arms long at the bottom up to chin near the handles; elbow flexes to roughly 58°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "assisted-pull-up-machine",
      name: "Assisted Pull-Up Machine",
      category: "pull",
      dbCategory: "other",
      dbSlug: "assisted_pull_up_machine",
      equipment: ["Machine"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, upper body and arms in frame",
      setupCue: "Face the camera with your torso and arms in view.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 168,
      activeAngle: 58,
      minRepFraction: 0.65,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Pull to the same height each rep and lower with control.",
    },
  },
  // ---------------------------------------------------------------- cable lat pushdown (straight-arm)
  {
    meta: {
      slug: "cable_lat_pushdown",
      name: "Straight-Arm Pulldown",
      aliases: ["straight arm pulldown", "cable lat pushdown", "lat pushdown"],
      primaryMuscles: ["lats"],
      secondaryMuscles: [],
      equipment: ["cable"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set a high pulley and stand facing the stack, hips hinged slightly.",
        "Grab the bar with fairly straight arms out in front of you.",
        "Sweep the bar down toward your thighs, keeping your arms long.",
        "Let the bar rise back up in front of you under control.",
      ],
      formPoints: [
        "Keep your arms fairly straight and move at the shoulders.",
        "Sweep the bar down to your thighs and feel your lats work.",
        "Keep your torso still rather than bobbing up and down.",
        "Control the bar back up on the same path.",
      ],
      commonMistakes: [
        "Bending the elbows and turning it into a pushdown.",
        "Using the torso to drive the bar down.",
        "Cutting the sweep short at the bottom.",
      ],
      romGuideline: "Arms forward and high sweeping down toward the thighs; measured angle closes to roughly 10°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "cable-lat-pushdown",
      name: "Straight-Arm Pulldown",
      category: "pull",
      dbCategory: "other",
      dbSlug: "cable_lat_pushdown",
      equipment: ["Cable"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, torso and arms in frame",
      setupCue: "Stand side-on to the camera with your arms in view.",
      keyJoints: hipTriplet,
      measure: angleMeasure("hip", "shoulder", "elbow", "best"),
      restAngle: 40,
      activeAngle: 10,
      minRepFraction: 0.5,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Keep your arms long and sweep to the same point each rep.",
    },
  },
  // ---------------------------------------------------------------- smith machine squat
  {
    meta: {
      slug: "smith_machine_squat",
      name: "Smith Machine Squat",
      aliases: ["smith machine squat", "smith squat"],
      primaryMuscles: ["quads", "glutes"],
      secondaryMuscles: ["hamstrings"],
      equipment: ["machine"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the bar across your upper back and unrack by rotating it free.",
        "Set your feet about shoulder-width, slightly ahead of the bar path.",
        "Brace and squat down until your thighs are about parallel.",
        "Drive up through your whole foot to a tall finish.",
      ],
      formPoints: [
        "Lower until your thighs reach about parallel for a full range.",
        "Track your knees out in line with your feet.",
        "Keep your whole foot planted and drive up with control.",
        "Match the same depth on every rep.",
      ],
      commonMistakes: [
        "Cutting depth short under heavier loads.",
        "Letting the knees cave inward.",
        "Bouncing out of the bottom.",
      ],
      romGuideline: "Thighs to about parallel; knee to roughly 92° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "smith-machine-squat",
      name: "Smith Machine Squat",
      category: "legs",
      dbCategory: "other",
      dbSlug: "smith_machine_squat",
      equipment: ["Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "3-1-1-0",
      camera: "Side view, full body from head to feet",
      setupCue: "Set the machine side-on with your whole body in frame.",
      keyJoints: ["hip", "knee", "ankle"],
      measure: angleMeasure("hip", "knee", "ankle", "min"),
      restAngle: 170,
      activeAngle: 92,
      minRepFraction: 0.65,
      formChecks: [],
      focus: ["depth", "control", "tempo"],
      reviewCue: "Match your depth each rep and drive up with control.",
    },
  },
  // ---------------------------------------------------------------- incline chest press machine
  {
    meta: {
      slug: "incline_chest_press_machine",
      name: "Incline Chest Press Machine",
      aliases: ["incline chest press machine", "incline press machine", "incline machine press"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["shoulders", "triceps"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the seat so the handles line up with your upper chest.",
        "Sit back against the inclined pad and grab the handles.",
        "Press the handles up and forward until your arms are nearly long.",
        "Let the handles return toward your upper chest under control.",
      ],
      formPoints: [
        "Press smoothly and stop just short of locking the elbows.",
        "Keep your back and shoulders settled against the pad.",
        "Let the handles return to about upper-chest level for a full range.",
        "Control the return rather than letting it snap back.",
      ],
      commonMistakes: [
        "Pressing only partway out.",
        "Lifting the hips or shoulders off the pad.",
        "Letting the stack pull the handles back too fast.",
      ],
      romGuideline: "Handles at the upper chest out to near-extended arms; elbow opens to roughly 168°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "incline-chest-press-machine",
      name: "Incline Chest Press Machine",
      category: "push",
      dbCategory: "other",
      dbSlug: "incline_chest_press_machine",
      equipment: ["Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, chest and arms in frame",
      setupCue: "Set the machine side-on so your arms are visible.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 90,
      activeAngle: 168,
      minRepFraction: 0.7,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Press to the same point each rep and control the return.",
    },
  },
  // ---------------------------------------------------------------- reverse pec deck
  {
    meta: {
      slug: "reverse_pec_deck",
      name: "Reverse Pec Deck",
      aliases: ["reverse pec deck", "rear delt machine", "reverse fly machine"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["back"],
      equipment: ["machine"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set the seat and handles so your arms start out in front at chest height.",
        "Sit facing the pad with your chest against it and grab the handles.",
        "Sweep your arms out and back in a wide arc, leading with the elbows.",
        "Return your arms to the front under control.",
      ],
      formPoints: [
        "Lead with your elbows and sweep your arms back in an arc.",
        "Keep your chest against the pad and your torso still.",
        "Open until your arms are roughly in line with your shoulders.",
        "Control the return rather than letting the stack snap the arms in.",
      ],
      commonMistakes: [
        "Shrugging the shoulders up toward the ears.",
        "Using momentum to fling the arms back.",
        "Cutting the range short at the back.",
      ],
      romGuideline: "Arms forward at the start out to level with the shoulders; measured angle opens to roughly 80°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "reverse-pec-deck",
      name: "Reverse Pec Deck",
      category: "pull",
      dbCategory: "other",
      dbSlug: "reverse_pec_deck",
      equipment: ["Machine"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, shoulders and both arms in frame",
      setupCue: "Frame the camera so your shoulders and arms are visible.",
      keyJoints: hipTriplet,
      measure: angleMeasure("hip", "shoulder", "elbow", "best"),
      restAngle: 20,
      activeAngle: 80,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Sweep your arms to the same point each rep and control the return.",
    },
  },
  // ---------------------------------------------------------------- single-arm cable row
  {
    meta: {
      slug: "cable_row_single_arm",
      name: "Single-Arm Cable Row",
      aliases: ["single arm cable row", "one arm cable row", "unilateral cable row"],
      primaryMuscles: ["back", "lats"],
      secondaryMuscles: ["biceps"],
      equipment: ["cable"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set a low or mid pulley and grab the handle in one hand.",
        "Sit or stand tall with that arm extended toward the stack.",
        "Pull the handle to your side, driving your elbow back past your torso.",
        "Let the handle travel forward under control, then finish and switch hands.",
      ],
      formPoints: [
        "Lead with your elbow and draw it past your torso.",
        "Keep your torso square and stable rather than twisting for reach.",
        "Pull to about your side for a full, consistent range.",
        "Control the return and match your work on both arms.",
      ],
      commonMistakes: [
        "Rotating the torso to yank the handle back.",
        "Shrugging the shoulder up toward the ear.",
        "Uneven range or effort between arms.",
      ],
      romGuideline: "Arm extended to the handle at the side; elbow flexes to roughly 75°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "cable-row-single-arm",
      name: "Single-Arm Cable Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "cable_row_single_arm",
      equipment: ["Cable"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view, torso and the working arm in frame",
      setupCue: "Stand side-on to the camera with the working arm in view.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 75,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Pull to the same point and match your work on both arms.",
    },
  },
];
