// MOBILITY — warm-up drills and mobility work. Two flavours live here:
//   Tier 1: drills a single camera can honestly rep-count or time (bird dog,
//     dead bug, standing toe touch). These carry a full MovementDef.
//   Tier 3: stretches and warm-up drills where one camera can't honestly score
//     the movement, so they are metadata-only (timer / manual logging).
//
// Copy stays practical and claim-safe: "move through a comfortable range",
// "warm up", "control" — never therapeutic, rehab, or clinical framing.

import { depthCheck } from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, hipTriplet } from "./_shared";

export const mobility: ExerciseEntry[] = [
  // ============================================================ TIER 1 (tracked)
  // ---------------------------------------------------------------- bird dog
  {
    meta: {
      slug: "bird_dog",
      name: "Bird Dog",
      aliases: ["bird dog", "birddog", "quadruped reach"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["glutes", "shoulders", "back"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Start on all fours with your hands under your shoulders and knees under your hips.",
        "Brace your core so your back stays flat and steady.",
        "Reach one arm forward and the opposite leg back until both line up with your torso.",
        "Pause briefly, return under control, then switch sides.",
      ],
      formPoints: [
        "Extend the leg through a comfortable range until it lines up with your torso.",
        "Keep your hips and shoulders level rather than twisting toward the reaching side.",
        "Move slowly and stay balanced instead of swinging the limbs.",
        "Keep your neck long and your gaze down at the floor.",
      ],
      commonMistakes: [
        "Twisting the hips open as the leg extends.",
        "Arching the lower back instead of staying flat.",
        "Rushing so the reach never fully extends.",
      ],
      romGuideline: "Extending leg reaches until it lines up with the torso; hip opens toward ~170°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "bird-dog",
      name: "Bird Dog",
      category: "core",
      dbCategory: "mobility_drill",
      dbSlug: "bird_dog",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view on all fours, shoulders through ankles visible",
      setupCue: "Set up on all fours, side-on to the camera.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 120,
      activeAngle: 172,
      minRepFraction: 0.6,
      formChecks: [depthCheck("Reach the leg back until it lines up with your torso.", 0.6)],
      focus: ["range", "balance", "control"],
      reviewCue: "Keep your hips level and extend fully on each side.",
    },
  },
  // ---------------------------------------------------------------- dead bug
  {
    meta: {
      slug: "dead_bug",
      name: "Dead Bug",
      aliases: ["dead bug", "deadbug"],
      primaryMuscles: ["core"],
      secondaryMuscles: ["hip_flexors"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Lie on your back with your arms reaching up and your knees stacked over your hips.",
        "Press your lower back gently into the floor and brace your core.",
        "Lower one leg toward the floor while keeping your back flat.",
        "Return under control, then work the other side.",
      ],
      formPoints: [
        "Lower the leg through a comfortable range while keeping your back flat.",
        "Move slowly and keep the motion controlled.",
        "Keep your ribs down rather than letting your back arch up.",
        "Breathe steadily as you extend and return.",
      ],
      commonMistakes: [
        "Letting the lower back arch off the floor.",
        "Dropping the leg quickly instead of controlling it.",
        "Holding your breath through the reps.",
      ],
      romGuideline: "Leg lowers toward the floor while the back stays flat; hip opens toward ~150°.",
      tutTarget: [2, 4],
    },
    def: {
      id: "dead-bug",
      name: "Dead Bug",
      category: "core",
      dbCategory: "mobility_drill",
      dbSlug: "dead_bug",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Side view lying down, torso and legs visible",
      setupCue: "Lie side-on to the camera with your arms and legs up.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "min"),
      restAngle: 150,
      activeAngle: 100,
      minRepFraction: 0.5,
      formChecks: [depthCheck("Lower the leg a little further while keeping your back flat.", 0.5)],
      focus: ["range", "control", "tempo"],
      reviewCue: "Keep your back flat and move each side with control.",
    },
  },
  // ---------------------------------------------------------------- standing toe touch
  {
    meta: {
      slug: "standing_toe_touch",
      name: "Standing Toe Touch",
      aliases: ["standing toe touch", "toe touch", "standing forward fold"],
      primaryMuscles: ["hamstrings"],
      secondaryMuscles: ["lower_back", "glutes"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Stand tall with your feet about hip-width apart.",
        "Hinge at your hips and reach your hands down toward your toes.",
        "Go only as far as feels comfortable, letting your upper body relax down.",
        "Rise back up with control to a tall stand, then repeat.",
      ],
      formPoints: [
        "Reach down through a comfortable range rather than forcing the stretch.",
        "Let your hips lead the hinge as your hands travel toward your toes.",
        "Keep the movement smooth and controlled in both directions.",
        "Rise back up steadily to a tall finish.",
      ],
      commonMistakes: [
        "Bouncing at the bottom to reach further.",
        "Rushing back up instead of controlling the return.",
        "Rounding sharply rather than hinging from the hips.",
      ],
      romGuideline: "Hinge forward through a comfortable range as the hands travel toward the toes.",
      tutTarget: [2, 4],
    },
    def: {
      id: "standing-toe-touch",
      name: "Standing Toe Touch",
      category: "core",
      dbCategory: "mobility_drill",
      dbSlug: "standing_toe_touch",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 2 },
      tempo: "2-1-2-0",
      camera: "Side view, full body from head to feet",
      setupCue: "Stand tall side-on with your whole body in frame.",
      keyJoints: hipTriplet,
      measure: angleMeasure("shoulder", "hip", "knee", "best"),
      restAngle: 172,
      activeAngle: 95,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Hinge to a comfortable range and rise up with control.",
    },
  },
  // ============================================================ TIER 3 (meta only)
  // ---------------------------------------------------------------- cat-cow
  {
    meta: {
      slug: "cat_cow",
      name: "Cat-Cow",
      aliases: ["cat cow", "cat-cow", "cat camel"],
      primaryMuscles: ["core", "lower_back"],
      secondaryMuscles: ["obliques"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Start on all fours with your hands under your shoulders and knees under your hips.",
        "Round your back gently toward the ceiling and let your head drop.",
        "Reverse the motion, dropping your belly and lifting your chest and gaze.",
        "Alternate smoothly between the two positions in time with your breath.",
      ],
      formPoints: [
        "Move through a comfortable range in both directions.",
        "Let each position flow into the next rather than forcing the end range.",
        "Keep the pace slow and matched to your breathing.",
        "Spread the motion across your whole spine, not just one spot.",
      ],
      commonMistakes: [
        "Rushing through the range instead of moving smoothly.",
        "Only moving the low back and skipping the upper spine.",
      ],
      romGuideline: "Alternate gentle spinal rounding and arching through a comfortable range.",
      tutTarget: [2, 5],
    },
  },
  // ---------------------------------------------------------------- world's greatest stretch
  {
    meta: {
      slug: "world_greatest_stretch",
      name: "World's Greatest Stretch",
      aliases: ["world's greatest stretch", "worlds greatest stretch", "wgs"],
      primaryMuscles: ["hip_flexors", "hamstrings"],
      secondaryMuscles: ["core", "shoulders"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Step into a long forward lunge with your front foot flat.",
        "Place both hands on the floor inside your front foot.",
        "Rotate your inside arm up toward the ceiling, opening through your chest.",
        "Return your hand to the floor, step back, and repeat on the other side.",
      ],
      formPoints: [
        "Open through your upper back and reach through a comfortable range.",
        "Keep your front foot flat as you settle into the lunge.",
        "Move smoothly between the reach-down and the rotation.",
        "Warm up gradually rather than forcing the end position.",
      ],
      commonMistakes: [
        "Rushing the rotation instead of controlling it.",
        "Letting the front heel lift off the floor.",
        "Skipping the reach and only holding the lunge.",
      ],
      romGuideline: "Settle into a lunge and rotate the torso open through a comfortable range.",
      tutTarget: [2, 5],
    },
  },
  // ---------------------------------------------------------------- hip flexor stretch
  {
    meta: {
      slug: "hip_flexor_stretch",
      name: "Hip Flexor Stretch",
      aliases: ["hip flexor stretch", "kneeling hip flexor stretch", "couch stretch"],
      primaryMuscles: ["hip_flexors"],
      secondaryMuscles: ["quads"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Kneel on one knee with the other foot planted flat in front of you.",
        "Keep your torso tall and your hips square to the front.",
        "Gently shift your weight forward until you feel a comfortable stretch at the front of the hip.",
        "Hold, then switch to the other side.",
      ],
      formPoints: [
        "Shift forward only to a comfortable range at the front of the hip.",
        "Keep your torso tall rather than leaning forward.",
        "Squeeze the glute on the kneeling side to settle into the position.",
        "Breathe steadily and stay relaxed through the hold.",
      ],
      commonMistakes: [
        "Leaning the torso forward instead of staying tall.",
        "Letting the front knee drift far past the toes.",
      ],
      romGuideline: "Shift the hips forward to a comfortable stretch at the front of the hip and hold.",
      tutTarget: [2, 5],
    },
  },
  // ---------------------------------------------------------------- hamstring stretch
  {
    meta: {
      slug: "hamstring_stretch",
      name: "Hamstring Stretch",
      aliases: ["hamstring stretch", "seated hamstring stretch", "standing hamstring stretch"],
      primaryMuscles: ["hamstrings"],
      secondaryMuscles: ["calves", "lower_back"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Sit or stand with one leg extended fairly straight.",
        "Hinge from your hips and reach toward the toes of the straight leg.",
        "Go only as far as feels comfortable behind the thigh.",
        "Hold the position, then switch legs.",
      ],
      formPoints: [
        "Hinge from the hips and reach through a comfortable range.",
        "Keep the working leg fairly straight without locking it hard.",
        "Let your upper body relax down rather than forcing the reach.",
        "Breathe steadily through the hold.",
      ],
      commonMistakes: [
        "Bouncing to reach further.",
        "Rounding hard through the back instead of hinging from the hips.",
      ],
      romGuideline: "Hinge forward over a straight leg to a comfortable stretch behind the thigh.",
      tutTarget: [2, 5],
    },
  },
  // ---------------------------------------------------------------- thoracic rotation
  {
    meta: {
      slug: "thoracic_rotation",
      name: "Thoracic Rotation",
      aliases: ["thoracic rotation", "t-spine rotation", "open book"],
      primaryMuscles: ["obliques", "back"],
      secondaryMuscles: ["shoulders", "core"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Set up on all fours or lie on your side with your arms out in front.",
        "Place one hand behind your head or reach it across your body.",
        "Rotate your upper back to open your chest toward the ceiling.",
        "Return under control and repeat, then switch sides.",
      ],
      formPoints: [
        "Rotate through your upper back to a comfortable range.",
        "Keep your hips steady so the motion comes from your torso.",
        "Follow your moving hand with your eyes to encourage the rotation.",
        "Move smoothly rather than snapping into the turn.",
      ],
      commonMistakes: [
        "Rotating from the hips instead of the upper back.",
        "Forcing the end range instead of moving smoothly.",
      ],
      romGuideline: "Rotate the upper back open through a comfortable range while the hips stay steady.",
      tutTarget: [2, 5],
    },
  },
  // ---------------------------------------------------------------- shoulder dislocate (band)
  {
    meta: {
      slug: "shoulder_dislocate_band",
      name: "Band Shoulder Pass-Through",
      aliases: ["shoulder dislocate", "band pass-through", "band shoulder dislocate"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["chest", "traps"],
      equipment: ["band"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Hold a band with a wide grip in front of your hips.",
        "Keep your arms fairly straight and raise the band overhead.",
        "Continue the arc behind you as far as feels comfortable.",
        "Reverse the path smoothly back to the front and repeat.",
      ],
      formPoints: [
        "Move through a comfortable range and widen your grip if the arc feels tight.",
        "Keep your arms fairly straight throughout the pass.",
        "Move smoothly rather than forcing the band behind you.",
        "Keep your ribs down and your torso tall.",
      ],
      commonMistakes: [
        "Gripping too narrow and straining at the back of the arc.",
        "Arching the back to force the band around.",
      ],
      romGuideline: "Pass the band overhead and behind through a comfortable range with straight arms.",
      tutTarget: [2, 4],
    },
  },
  // ---------------------------------------------------------------- ankle mobility drill
  {
    meta: {
      slug: "ankle_mobility_drill",
      name: "Ankle Mobility Drill",
      aliases: ["ankle mobility", "ankle mobility drill", "knee-to-wall"],
      primaryMuscles: ["calves"],
      secondaryMuscles: ["quads"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Set up in a half-kneeling or split stance facing a wall.",
        "Keep your front heel planted and drive your knee forward toward the wall.",
        "Move through a comfortable range, letting the ankle bend.",
        "Return and repeat, then switch sides.",
      ],
      formPoints: [
        "Drive the knee forward over the toes through a comfortable range.",
        "Keep your front heel flat on the floor throughout.",
        "Move slowly and control each rep.",
        "Track your knee over the middle of your foot.",
      ],
      commonMistakes: [
        "Letting the heel lift as the knee travels forward.",
        "Rushing the reps instead of moving with control.",
      ],
      romGuideline: "Drive the knee forward over the toes with the heel down through a comfortable range.",
      tutTarget: [2, 4],
    },
  },
  // ---------------------------------------------------------------- arm circles
  {
    meta: {
      slug: "arm_circles",
      name: "Arm Circles",
      aliases: ["arm circles", "shoulder circles"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["traps"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Stand tall and reach both arms out to your sides.",
        "Draw small circles with your hands and gradually make them larger.",
        "Move through a comfortable range in one direction.",
        "Reverse the direction and repeat to warm up the shoulders.",
      ],
      formPoints: [
        "Start small and build to a comfortable range as you warm up.",
        "Keep your torso tall and steady while your arms move.",
        "Move smoothly rather than swinging hard.",
        "Circle in both directions for even coverage.",
      ],
      commonMistakes: [
        "Starting with big, fast circles before warming up.",
        "Shrugging the shoulders up toward the ears.",
      ],
      romGuideline: "Circle the arms through a growing, comfortable range in both directions.",
      tutTarget: [2, 4],
    },
  },
  // ---------------------------------------------------------------- leg swings
  {
    meta: {
      slug: "leg_swings",
      name: "Leg Swings",
      aliases: ["leg swings", "dynamic leg swings"],
      primaryMuscles: ["hip_flexors", "hamstrings"],
      secondaryMuscles: ["glutes", "adductors"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 3,
      loadType: "bodyweight",
      instructions: [
        "Stand next to a wall or support and hold on for balance.",
        "Swing one leg forward and back through a comfortable range.",
        "Keep your torso tall and let the leg move freely.",
        "Repeat for reps, then switch to the other leg.",
      ],
      formPoints: [
        "Swing through a comfortable range that grows as you warm up.",
        "Keep your torso tall and steady while the leg moves.",
        "Let the swing stay smooth rather than forcing height.",
        "Hold a support so you can stay balanced.",
      ],
      commonMistakes: [
        "Swinging hard before the hips are warm.",
        "Leaning the torso far to counter the swing.",
      ],
      romGuideline: "Swing the leg through a growing, comfortable range while the torso stays tall.",
      tutTarget: [1, 3],
    },
  },
];
