// PULL — horizontal and vertical rowing / pull-up family (back, lat and biceps
// dominant elbow-flexion patterns).
// Tier 1 movements: full MovementDef + form checks, side/front camera views.
// Elbow angles follow mainstream strength-coaching standards (rows: arm ~160-168°
// extended, ~65-75° pulled; pull-ups: ~168° dead hang, ~50-55° chin over the bar),
// widened slightly for single-camera landmark noise.

import { depthCheck, flatBackCheck } from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, elbowTriplet } from "./_shared";

export const pull: ExerciseEntry[] = [
  // ---------------------------------------------------------------- bent-over row (existing)
  {
    meta: {
      slug: "bent_over_row",
      name: "Bent-Over Row",
      aliases: ["bent over row", "bent-over row", "dumbbell bent over row"],
      primaryMuscles: ["back", "lats"],
      secondaryMuscles: ["biceps", "traps", "shoulders"],
      equipment: ["dumbbell", "barbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Hinge at your hips until your torso is close to parallel with the floor.",
        "Let the weights hang at arm's length with a soft bend in your knees.",
        "Pull the weights toward your lower ribs, leading with your elbows.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Keep a flat, braced back throughout the set.",
        "Drive your elbows back rather than shrugging the weight up.",
        "Pull to about the level of your lower ribs each rep.",
        "Control the way down to a full stretch.",
      ],
      commonMistakes: [
        "Standing up out of the hinge as the set goes on.",
        "Yanking with the lower back instead of the arms.",
        "Cutting the range short at the bottom.",
      ],
      romGuideline: "Arm from about straight to a strong pull; elbow ~160° to ~70° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "bent-over-row",
      name: "Bent-Over Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "bent_over_row",
      equipment: ["Dumbbells", "Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, full body and the weights visible",
      setupCue: "Hinge forward side-on to the camera with the weights in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 160,
      activeAngle: 70,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Pull a little higher — bring the weight to your ribs.", 0.6),
      ],
      focus: ["range", "posture", "control"],
      reviewCue: "Hold the hinge and pull to the same height each rep.",
    },
  },
  // ---------------------------------------------------------------- single-arm dumbbell row
  {
    meta: {
      slug: "single_arm_dumbbell_row",
      name: "Single-Arm Dumbbell Row",
      aliases: ["one arm dumbbell row", "single arm dumbbell row", "one-arm row"],
      primaryMuscles: ["lats", "back"],
      secondaryMuscles: ["biceps", "traps"],
      equipment: ["dumbbell", "bench"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Brace one hand and knee on a bench with your back flat and near parallel.",
        "Let the dumbbell hang at arm's length from your working side.",
        "Pull the dumbbell toward your hip, leading with your elbow.",
        "Lower under control to a full stretch, finish your reps, then switch sides.",
      ],
      formPoints: [
        "Keep a flat, steady back with your hips square through the set.",
        "Drive your elbow back and toward your hip rather than shrugging.",
        "Pull to about hip height for a full contraction.",
        "Lower slowly to a full stretch each rep.",
      ],
      commonMistakes: [
        "Twisting the torso to heave the weight up.",
        "Rounding the back out of the braced position.",
        "Short reps that skip the stretch at the bottom.",
      ],
      romGuideline: "Arm from about straight to a strong pull; elbow ~162° to ~68° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "single-arm-dumbbell-row",
      name: "Single-Arm Dumbbell Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "single_arm_dumbbell_row",
      equipment: ["Dumbbell", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, torso and the bench visible",
      setupCue: "Brace on the bench side-on to the camera with the weight in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 162,
      activeAngle: 68,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Pull higher — bring the dumbbell toward your hip.", 0.6),
        flatBackCheck("Keep your back flat and steady."),
      ],
      focus: ["range", "posture", "control"],
      reviewCue: "Hold a flat back and match your range on both sides.",
    },
  },
  // ---------------------------------------------------------------- pull-up
  {
    meta: {
      slug: "pull_up",
      name: "Pull-Up",
      aliases: ["pull up", "pull-up", "pullup"],
      primaryMuscles: ["lats"],
      secondaryMuscles: ["biceps", "back", "forearms"],
      equipment: ["pull_up_bar"],
      difficulty: "advanced",
      tier: 1,
      loadType: "both",
      instructions: [
        "Hang from the bar with an overhand grip a little wider than your shoulders.",
        "Start from a full hang with your arms straight.",
        "Pull your chest toward the bar, driving your elbows down and back.",
        "Bring your chin over the bar, then lower under control to a full hang.",
      ],
      formPoints: [
        "Begin each rep from a full dead hang.",
        "Lead with your elbows down toward your ribs.",
        "Aim to bring your chin over the bar each rep.",
        "Lower slowly rather than dropping into the hang.",
      ],
      commonMistakes: [
        "Short reps that stop well below the bar.",
        "Kipping or swinging to get up.",
        "Not returning to a full hang between reps.",
      ],
      romGuideline: "Full hang to chin over the bar; elbow ~168° to ~55° front view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "pull-up",
      name: "Pull-Up",
      category: "pull",
      dbCategory: "other",
      dbSlug: "pull_up",
      equipment: ["Bodyweight", "Pull-Up Bar"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 6, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, full body and the bar visible",
      setupCue: "Face the camera hanging from the bar with your whole body in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      // Camera-measured: a chin-over-bar top MEASURES ~65-80° elbow in 3D
      // (z noise opens deep flexion), not the anatomical ~55°.
      restAngle: 168,
      activeAngle: 65,
      minRepFraction: 0.68,
      formChecks: [
        depthCheck("Pull higher — aim to bring your chin over the bar.", 0.68),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Start from a full hang and pull to the same height each rep.",
    },
  },
  // ---------------------------------------------------------------- chin-up
  {
    meta: {
      slug: "chin_up",
      name: "Chin-Up",
      aliases: ["chin up", "chin-up", "chinup"],
      primaryMuscles: ["biceps", "lats"],
      secondaryMuscles: ["back", "forearms"],
      equipment: ["pull_up_bar"],
      difficulty: "advanced",
      tier: 1,
      loadType: "both",
      instructions: [
        "Hang from the bar with an underhand grip about shoulder-width apart.",
        "Start from a full hang with your arms straight.",
        "Pull your chest toward the bar, driving your elbows down.",
        "Bring your chin over the bar, then lower under control to a full hang.",
      ],
      formPoints: [
        "Begin each rep from a full dead hang.",
        "Drive your elbows down toward your sides.",
        "Aim to bring your chin over the bar each rep.",
        "Lower slowly to a full hang rather than dropping.",
      ],
      commonMistakes: [
        "Stopping short well below the bar.",
        "Swinging or kipping to finish the rep.",
        "Skipping the full hang between reps.",
      ],
      romGuideline: "Full hang to chin over the bar; elbow ~168° to ~52° front view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "chin-up",
      name: "Chin-Up",
      category: "pull",
      dbCategory: "other",
      dbSlug: "chin_up",
      equipment: ["Bodyweight", "Pull-Up Bar"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 6, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, full body and the bar visible",
      setupCue: "Face the camera hanging from the bar with your whole body in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 168,
      activeAngle: 62,
      minRepFraction: 0.68,
      formChecks: [
        depthCheck("Pull higher — aim to bring your chin over the bar.", 0.68),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Start from a full hang and pull to the same height each rep.",
    },
  },
  // ---------------------------------------------------------------- inverted row
  {
    meta: {
      slug: "inverted_row",
      name: "Inverted Row",
      aliases: ["inverted row", "bodyweight row", "australian pull up"],
      primaryMuscles: ["back", "lats"],
      secondaryMuscles: ["biceps", "traps"],
      equipment: ["bodyweight", "barbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Set a bar at about waist height and lie underneath it.",
        "Grip the bar a little wider than your shoulders with your body in a straight line.",
        "Pull your chest toward the bar, driving your elbows back.",
        "Lower under control until your arms are straight, then repeat.",
      ],
      formPoints: [
        "Keep your body in a straight line from shoulders to heels.",
        "Drive your elbows back and pull your chest to the bar.",
        "Squeeze your shoulder blades together at the top.",
        "Lower slowly to full arm extension each rep.",
      ],
      commonMistakes: [
        "Letting the hips sag out of the straight line.",
        "Short reps that stop well short of the bar.",
        "Rushing the lowering phase.",
      ],
      romGuideline: "Straight arms to chest near the bar; elbow ~168° to ~65° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "inverted-row",
      name: "Inverted Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "inverted_row",
      equipment: ["Bodyweight", "Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, full body and the bar visible",
      setupCue: "Lie under the bar side-on to the camera with your whole body in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 168,
      activeAngle: 70,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Pull higher — bring your chest toward the bar.", 0.6),
      ],
      focus: ["range", "posture", "control"],
      reviewCue: "Hold a straight body line and pull to the same height each rep.",
    },
  },
  // ---------------------------------------------------------------- barbell row
  {
    meta: {
      slug: "barbell_row",
      name: "Barbell Row",
      aliases: ["barbell row", "bent over barbell row", "pendlay row"],
      primaryMuscles: ["back", "lats", "traps"],
      secondaryMuscles: ["biceps", "lower_back"],
      equipment: ["barbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Hinge at your hips until your torso is close to parallel with the floor.",
        "Hold the bar at arm's length with a soft bend in your knees.",
        "Pull the bar toward your lower ribs, leading with your elbows.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Keep a flat, braced back throughout the set.",
        "Drive your elbows back rather than shrugging the bar up.",
        "Pull the bar to about the level of your lower ribs.",
        "Control the way down to a full stretch.",
      ],
      commonMistakes: [
        "Standing up out of the hinge as the set goes on.",
        "Heaving with the lower back instead of the arms.",
        "Cutting the range short at the bottom.",
      ],
      romGuideline: "Arm from about straight to a strong pull; elbow ~160° to ~68° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "barbell-row",
      name: "Barbell Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "barbell_row",
      equipment: ["Barbell"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 4 },
      tempo: "2-1-1-0",
      camera: "Side view, full body and the bar visible",
      setupCue: "Hinge forward side-on to the camera with the bar in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 160,
      activeAngle: 68,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Pull a little higher — bring the bar to your ribs.", 0.6),
        flatBackCheck("Keep your back flat and hold the hinge."),
      ],
      focus: ["range", "posture", "control"],
      reviewCue: "Hold the hinge and pull to the same height each rep.",
    },
  },
  // ---------------------------------------------------------------- t-bar row
  {
    meta: {
      slug: "t_bar_row",
      name: "T-Bar Row",
      aliases: ["t bar row", "t-bar row", "landmine row"],
      primaryMuscles: ["back", "lats"],
      secondaryMuscles: ["biceps", "traps"],
      equipment: ["barbell", "machine"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Straddle the bar and hinge at your hips with a flat back.",
        "Take the handles and let the weight hang at arm's length.",
        "Pull the handles toward your torso, leading with your elbows.",
        "Lower under control to a full stretch, then repeat.",
      ],
      formPoints: [
        "Keep a flat, braced back throughout the set.",
        "Drive your elbows back rather than shrugging the weight up.",
        "Pull to about the level of your torso each rep.",
        "Control the way down to a full stretch.",
      ],
      commonMistakes: [
        "Standing up out of the hinge as the set goes on.",
        "Jerking with the lower back instead of the arms.",
        "Cutting the range short at the bottom.",
      ],
      romGuideline: "Arm from about straight to a strong pull; elbow ~160° to ~70° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "t-bar-row",
      name: "T-Bar Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "t_bar_row",
      equipment: ["Barbell", "Machine"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, full body and the handles visible",
      setupCue: "Hinge over the bar side-on to the camera with the handles in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 160,
      activeAngle: 70,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Pull a little higher — bring the weight to your torso.", 0.6),
        flatBackCheck("Keep your back flat and hold the hinge."),
      ],
      focus: ["range", "posture", "control"],
      reviewCue: "Hold the hinge and pull to the same height each rep.",
    },
  },
  // ---------------------------------------------------------------- renegade row
  {
    meta: {
      slug: "renegade_row",
      name: "Renegade Row",
      aliases: ["renegade row", "plank row", "renegade dumbbell row"],
      primaryMuscles: ["back", "core"],
      secondaryMuscles: ["biceps", "shoulders"],
      equipment: ["dumbbell"],
      difficulty: "advanced",
      tier: 1,
      loadType: "external",
      instructions: [
        "Set up in a high plank with a hand on each dumbbell, feet wide for balance.",
        "Brace your core and keep your hips square to the floor.",
        "Row one dumbbell toward your hip, leading with your elbow.",
        "Lower under control, then row the other side, alternating each rep.",
      ],
      formPoints: [
        "Keep your hips square and steady rather than rotating.",
        "Set your feet wide for a stable base.",
        "Drive your elbow back and toward your hip on each row.",
        "Lower each dumbbell under control.",
      ],
      commonMistakes: [
        "Twisting the hips as you row.",
        "Feet too narrow, making the plank wobble.",
        "Rushing the reps and losing the plank position.",
      ],
      romGuideline: "Arm from about straight to a strong pull; elbow ~165° to ~70° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "renegade-row",
      name: "Renegade Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: "renegade_row",
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "side",
      unilateral: true,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view, full body and the weights visible",
      setupCue: "Set up in a plank side-on to the camera with the weights in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 70,
      minRepFraction: 0.6,
      formChecks: [
        depthCheck("Row higher — bring the dumbbell toward your hip.", 0.6),
      ],
      focus: ["range", "stability", "control"],
      reviewCue: "Keep your hips square and match your range on both sides.",
    },
  },
];
