// PUSH — horizontal and vertical pressing patterns (chest/triceps/shoulder
// dominant elbow-extension movements). Tier 1 movements: full MovementDef +
// form checks, side camera view. Angles follow mainstream strength-coaching
// standards (side view: elbow extension ~160-170° at the top, ~85-95° at the
// bottom of a press), widened slightly to tolerate single-camera landmark jitter.

import {
  bodyLineCheck,
  depthCheck,
  elbowFlareCheck,
} from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, elbowTriplet } from "./_shared";

export const push: ExerciseEntry[] = [
  // ---------------------------------------------------------------- push-up (existing)
  {
    meta: {
      slug: "strict_push_up",
      name: "Push-Up",
      aliases: ["push up", "push-up", "strict push up", "press up"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders", "core"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Set your hands a little wider than shoulder-width with your body in a straight line.",
        "Brace your core and squeeze your glutes so your hips stay level.",
        "Lower your chest toward the floor under control until your elbows reach about 90°.",
        "Press back up to a tall lockout, keeping your body in one line.",
      ],
      formPoints: [
        "Keep a straight line from your shoulders through your hips to your ankles.",
        "Lower until your elbows bend to about 90° for a consistent range.",
        "Let your elbows travel back at roughly 45° rather than flaring straight out.",
        "Move at a steady, controlled tempo on the way down and up.",
      ],
      commonMistakes: [
        "Letting the hips sag or pike out of the body line.",
        "Cutting the range short with shallow reps.",
        "Rushing the descent and bouncing off the bottom.",
      ],
      romGuideline: "Chest toward the floor; elbow bends to roughly 85-95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "push-up",
      name: "Push-Up",
      category: "push",
      dbCategory: "push_up",
      dbSlug: "strict_push_up",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulders, hips, and ankles visible",
      setupCue: "Set up side-on with your whole body in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 88,
      minRepFraction: 0.75,
      formChecks: [
        bodyLineCheck("Lift your hips into a straight line.", "Drop your hips level with your body."),
        depthCheck("Lower a little deeper — elbows toward 90°.", 0.75),
      ],
      focus: ["depth", "body line", "control"],
      reviewCue: "Keep one straight line and hit the same depth each rep.",
    },
  },
  // ---------------------------------------------------------------- incline push-up
  {
    meta: {
      slug: "incline_push_up",
      name: "Incline Push-Up",
      aliases: ["incline push up", "hands-elevated push up", "bench push up"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders", "core"],
      equipment: ["bodyweight", "bench", "box"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Place your hands on a bench, box, or sturdy surface a little wider than your shoulders.",
        "Walk your feet back so your body forms a straight line on an incline.",
        "Lower your chest toward the surface under control.",
        "Press back up to a tall lockout, keeping your hips level.",
      ],
      formPoints: [
        "Keep a straight line from your shoulders to your ankles the whole time.",
        "Lower until your chest is close to the surface for a full range.",
        "Guide your elbows back rather than letting them flare wide.",
        "Control the tempo down and up.",
      ],
      commonMistakes: [
        "Letting the hips sag toward the surface.",
        "Short reps that skip the bottom.",
        "Rushing the lowering phase.",
      ],
      romGuideline: "Chest toward the surface; elbow bends to roughly 90-100° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "incline-push-up",
      name: "Incline Push-Up",
      category: "push",
      dbCategory: "push_up",
      dbSlug: "incline_push_up",
      equipment: ["Bodyweight", "Bench", "Box"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulders, hips, and ankles visible",
      setupCue: "Set your hands on the surface, side-on to the camera.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 95,
      minRepFraction: 0.65,
      formChecks: [
        bodyLineCheck("Lift your hips into a straight line.", "Drop your hips level with your body."),
        depthCheck("Lower a little closer to the surface.", 0.65),
      ],
      focus: ["depth", "body line", "control"],
      reviewCue: "Keep a straight line and match your depth each rep.",
    },
  },
  // ---------------------------------------------------------------- knee push-up
  {
    meta: {
      slug: "knee_push_up",
      name: "Knee Push-Up",
      aliases: ["knee push up", "kneeling push up", "modified push up"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders", "core"],
      equipment: ["bodyweight"],
      difficulty: "beginner",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Kneel down and set your hands a little wider than shoulder-width.",
        "Keep a straight line from your shoulders through your hips to your knees.",
        "Lower your chest toward the floor under control until your elbows reach about 90°.",
        "Press back up to a tall lockout, keeping your hips from sagging.",
      ],
      formPoints: [
        "Hold a straight line from your shoulders to your knees.",
        "Lower until your elbows bend to about 90° for a full range.",
        "Guide your elbows back rather than letting them flare wide.",
        "Move at a steady, controlled pace.",
      ],
      commonMistakes: [
        "Letting the hips drop or push up out of line.",
        "Shallow reps that skip the bottom.",
        "Rushing the descent.",
      ],
      romGuideline: "Chest toward the floor; elbow bends to roughly 85-95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "knee-push-up",
      name: "Knee Push-Up",
      category: "push",
      dbCategory: "push_up",
      dbSlug: "knee_push_up",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulders, hips, and knees visible",
      setupCue: "Kneel side-on with your upper body clearly in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 90,
      minRepFraction: 0.7,
      formChecks: [
        bodyLineCheck("Lift your hips into a straight line.", "Drop your hips level with your body.", 0.14),
        depthCheck("Lower a little deeper — elbows toward 90°.", 0.7),
      ],
      focus: ["depth", "body line", "control"],
      reviewCue: "Keep shoulders-to-knees in one line and match your depth.",
    },
  },
  // ---------------------------------------------------------------- diamond push-up
  {
    meta: {
      slug: "diamond_push_up",
      name: "Diamond Push-Up",
      aliases: ["diamond push up", "triangle push up", "close grip push up"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: ["chest", "shoulders", "core"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Set your hands close together under your chest so your index fingers and thumbs form a diamond.",
        "Brace your core and hold a straight line from your shoulders to your ankles.",
        "Lower your chest toward your hands under control.",
        "Press back up to a tall lockout, keeping your elbows tracking close.",
      ],
      formPoints: [
        "Keep your elbows tucked close to your body as you lower.",
        "Hold a straight line from your shoulders through your hips to your ankles.",
        "Lower with control until your chest is near your hands.",
        "Press up with intent to a full lockout.",
      ],
      commonMistakes: [
        "Letting the hips sag or pike out of line.",
        "Flaring the elbows wide instead of keeping them close.",
        "Cutting the range short at the bottom.",
      ],
      romGuideline: "Chest toward your hands; elbow bends to roughly 85-95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "diamond-push-up",
      name: "Diamond Push-Up",
      category: "push",
      dbCategory: "push_up",
      dbSlug: "diamond_push_up",
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulders, hips, and ankles visible",
      setupCue: "Set up side-on with your whole body in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 168,
      activeAngle: 85,
      minRepFraction: 0.75,
      formChecks: [
        bodyLineCheck("Lift your hips into a straight line.", "Drop your hips level with your body."),
        depthCheck("Lower a little deeper toward your hands.", 0.75),
      ],
      focus: ["depth", "body line", "control"],
      reviewCue: "Keep your elbows close and hold the same depth each rep.",
    },
  },
  // ---------------------------------------------------------------- decline push-up
  {
    meta: {
      slug: "decline_push_up",
      name: "Decline Push-Up",
      aliases: ["decline push up", "feet-elevated push up"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["shoulders", "triceps", "core"],
      equipment: ["bodyweight", "bench", "box"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Set your hands on the floor a little wider than shoulder-width.",
        "Rest your feet on a bench or box so your body forms a straight decline.",
        "Brace your core and lower your chest toward the floor under control.",
        "Press back up to a tall lockout, keeping your hips level.",
      ],
      formPoints: [
        "Hold a straight line from your shoulders to your feet on the bench.",
        "Lower until your elbows bend to about 90° for a full range.",
        "Guide your elbows back rather than flaring them wide.",
        "Control the tempo down and up.",
      ],
      commonMistakes: [
        "Letting the hips pike up toward the ceiling.",
        "Short reps that skip the bottom.",
        "Rushing the descent.",
      ],
      romGuideline: "Chest toward the floor; elbow bends to roughly 85-95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "decline-push-up",
      name: "Decline Push-Up",
      category: "push",
      dbCategory: "push_up",
      dbSlug: "decline_push_up",
      equipment: ["Bodyweight", "Bench", "Box"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulders, hips, and feet on the bench visible",
      setupCue: "Rest your feet on the bench, side-on to the camera.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 88,
      minRepFraction: 0.75,
      formChecks: [
        bodyLineCheck("Lift your hips into a straight line.", "Drop your hips level with your body."),
        depthCheck("Lower a little deeper — elbows toward 90°.", 0.75),
      ],
      focus: ["depth", "body line", "control"],
      reviewCue: "Keep one straight line and match your depth each rep.",
    },
  },
  // ---------------------------------------------------------------- bench press
  {
    meta: {
      slug: "bench_press",
      name: "Barbell Bench Press",
      aliases: ["bench press", "barbell bench press", "flat bench press"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["barbell", "bench"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Lie back on a flat bench and grip the bar a little wider than shoulder-width.",
        "Set your feet flat and keep a steady, braced upper back.",
        "Unrack the bar and lower it under control toward your mid-chest.",
        "Press the bar back up to a tall lockout over your chest.",
      ],
      formPoints: [
        "Lower the bar to touch around your mid-chest for a consistent range.",
        "Keep your elbows tucked at roughly 45° rather than flaring straight out.",
        "Keep your wrists stacked over your elbows through the press.",
        "Control the descent, then press up with intent.",
      ],
      commonMistakes: [
        "Bouncing the bar off the chest.",
        "Flaring the elbows wide at the bottom.",
        "Cutting the range short and half-pressing.",
      ],
      romGuideline: "Bar to mid-chest; elbow bends to roughly 85-95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "bench-press",
      name: "Barbell Bench Press",
      category: "push",
      dbCategory: "other",
      dbSlug: "bench_press",
      equipment: ["Barbell", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 4 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulder, elbow, and wrist visible",
      setupCue: "Lie side-on to the camera with the bar path in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 85,
      minRepFraction: 0.75,
      formChecks: [
        depthCheck("Lower the bar closer to your chest.", 0.75),
        elbowFlareCheck("Tuck your elbows in a little on the way down."),
      ],
      focus: ["depth", "elbow path", "control"],
      reviewCue: "Touch the same spot on your chest and keep the elbows tucked.",
    },
  },
  // ---------------------------------------------------------------- dumbbell bench press
  {
    meta: {
      slug: "dumbbell_bench_press",
      name: "Dumbbell Bench Press",
      aliases: ["dumbbell bench press", "db bench press", "flat db press"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["dumbbell", "bench"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Lie back on a flat bench holding a dumbbell in each hand at chest level.",
        "Set your feet flat and keep a steady, braced upper back.",
        "Press the dumbbells up over your chest until your arms are tall.",
        "Lower them under control until your elbows reach about 90°, then repeat.",
      ],
      formPoints: [
        "Lower until your elbows bend to about 90° for a full range.",
        "Keep your elbows tucked at roughly 45° rather than flaring straight out.",
        "Press the dumbbells over your chest and stack your wrists.",
        "Control the descent, then press up with intent.",
      ],
      commonMistakes: [
        "Cutting the range short at the top.",
        "Flaring the elbows wide at the bottom.",
        "Letting the dumbbells drift out of control.",
      ],
      romGuideline: "Elbows to about 90° at the bottom; arms tall at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "dumbbell-bench-press",
      name: "Dumbbell Bench Press",
      category: "push",
      dbCategory: "other",
      dbSlug: "dumbbell_bench_press",
      equipment: ["Dumbbells", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulder, elbow, and wrist visible",
      setupCue: "Lie side-on to the camera with your press path in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 88,
      minRepFraction: 0.75,
      formChecks: [
        depthCheck("Lower a little deeper — elbows toward 90°.", 0.75),
        elbowFlareCheck("Tuck your elbows in a little on the way down."),
      ],
      focus: ["depth", "elbow path", "control"],
      reviewCue: "Match your bottom depth and keep the elbows tucked.",
    },
  },
  // ---------------------------------------------------------------- incline bench press
  {
    meta: {
      slug: "incline_bench_press",
      name: "Incline Barbell Bench Press",
      aliases: ["incline bench press", "incline barbell press", "incline press"],
      primaryMuscles: ["chest", "shoulders"],
      secondaryMuscles: ["triceps"],
      equipment: ["barbell", "bench"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Set a bench to a moderate incline and grip the bar a little wider than your shoulders.",
        "Set your feet flat and keep a steady, braced upper back.",
        "Unrack the bar and lower it under control toward your upper chest.",
        "Press the bar back up to a tall lockout over your upper chest.",
      ],
      formPoints: [
        "Lower the bar toward your upper chest for a consistent range.",
        "Keep your elbows tucked at roughly 45° rather than flaring straight out.",
        "Keep your wrists stacked over your elbows through the press.",
        "Control the descent, then press up with intent.",
      ],
      commonMistakes: [
        "Bouncing the bar off the chest.",
        "Flaring the elbows wide at the bottom.",
        "Half-pressing and cutting the range short.",
      ],
      romGuideline: "Bar to upper chest; elbow bends to roughly 85-95° side view.",
      tutTarget: [2, 4],
    },
    def: {
      id: "incline-bench-press",
      name: "Incline Barbell Bench Press",
      category: "push",
      dbCategory: "other",
      dbSlug: "incline_bench_press",
      equipment: ["Barbell", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 4 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulder, elbow, and wrist visible",
      setupCue: "Lie back on the incline side-on to the camera.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 88,
      minRepFraction: 0.75,
      formChecks: [
        depthCheck("Lower the bar closer to your upper chest.", 0.75),
        elbowFlareCheck("Tuck your elbows in a little on the way down."),
      ],
      focus: ["depth", "elbow path", "control"],
      reviewCue: "Touch the same spot on your upper chest and keep elbows tucked.",
    },
  },
  // ---------------------------------------------------------------- dumbbell chest press
  {
    meta: {
      slug: "dumbbell_chest_press",
      name: "Dumbbell Chest Press",
      aliases: ["dumbbell chest press", "db chest press", "db press"],
      primaryMuscles: ["chest"],
      secondaryMuscles: ["triceps", "shoulders"],
      equipment: ["dumbbell", "bench"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Lie back on a flat bench holding a dumbbell in each hand.",
        "Start with the dumbbells pressed tall over your chest.",
        "Lower them under control out to the sides until your elbows reach about 90°.",
        "Press back up over your chest to a tall finish, then repeat.",
      ],
      formPoints: [
        "Lower until your elbows bend to about 90° for a full range.",
        "Keep your elbows tucked at roughly 45° rather than flaring straight out.",
        "Press the dumbbells over your chest and stack your wrists.",
        "Control the descent, then press up with intent.",
      ],
      commonMistakes: [
        "Cutting the range short at the top.",
        "Flaring the elbows wide at the bottom.",
        "Letting the dumbbells wobble out of control.",
      ],
      romGuideline: "Elbows to about 90° at the bottom; arms tall at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "dumbbell-chest-press",
      name: "Dumbbell Chest Press",
      category: "push",
      dbCategory: "other",
      dbSlug: "dumbbell_chest_press",
      equipment: ["Dumbbells", "Bench"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulder, elbow, and wrist visible",
      setupCue: "Lie side-on to the camera with your press path in frame.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 88,
      minRepFraction: 0.75,
      formChecks: [
        depthCheck("Lower a little deeper — elbows toward 90°.", 0.75),
        elbowFlareCheck("Tuck your elbows in a little on the way down."),
      ],
      focus: ["depth", "elbow path", "control"],
      reviewCue: "Match your bottom depth and keep the elbows tucked.",
    },
  },
  // ---------------------------------------------------------------- dip
  {
    meta: {
      slug: "dip",
      name: "Dip",
      aliases: ["dips", "chest dip", "triceps dip", "parallel bar dip"],
      primaryMuscles: ["triceps"],
      secondaryMuscles: ["chest", "shoulders"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "both",
      instructions: [
        "Grip parallel bars and press up to a tall lockout with your arms straight.",
        "Keep your core braced and your shoulders down away from your ears.",
        "Lower under control until your elbows reach about 90°.",
        "Press back up to a tall lockout, then repeat.",
      ],
      formPoints: [
        "Lower until your elbows bend to about 90° for a full range.",
        "Keep your shoulders down and your torso steady as you lower.",
        "Control the descent rather than dropping into the bottom.",
        "Press up to a tall lockout on each rep.",
      ],
      commonMistakes: [
        "Short reps that skip the bottom range.",
        "Shrugging the shoulders up toward the ears.",
        "Dropping fast and bouncing out of the bottom.",
      ],
      romGuideline: "Elbows to about 90° at the bottom; tall lockout at the top (side view).",
      tutTarget: [2, 4],
    },
    def: {
      id: "dip",
      name: "Dip",
      category: "push",
      dbCategory: "other",
      dbSlug: "dip",
      equipment: ["Bodyweight", "Parallel bars"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulder, elbow, and hips visible",
      setupCue: "Set up on the bars side-on to the camera.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 85,
      minRepFraction: 0.75,
      formChecks: [
        depthCheck("Lower a little deeper — elbows toward 90°.", 0.75),
        bodyLineCheck("Keep your torso steady and stacked.", "Keep your torso steady and stacked."),
      ],
      focus: ["depth", "control", "shoulder position"],
      reviewCue: "Lower under control to the same depth and finish tall.",
    },
  },
];
