// SHOULDERS — overhead pressing and delt-raise patterns (shoulder-dominant
// abduction / vertical-press movements). Tier 1 movements carry a full
// MovementDef + form checks; tier 2 movements count reps but skip form judgment
// where a single camera can't read the load path honestly. Angles follow
// mainstream strength-coaching standards (front view: press lockout ~170°, arm
// raised to shoulder height ~85-90° of abduction), widened slightly to tolerate
// single-camera landmark jitter.

import {
  depthCheck,
  topHeightCheck,
  torsoStillCheck,
} from "../checks";
import type { ExerciseEntry } from "../types";
import { angleMeasure, elbowTriplet } from "./_shared";

// Arm-abduction driver for raises: hip->shoulder->elbow opens as the arm lifts
// away from the side (rest ~14°, arm to shoulder height ~88°).
const abductionMeasure = angleMeasure("hip", "shoulder", "elbow", "best");

export const shoulders: ExerciseEntry[] = [
  // ---------------------------------------------------------------- overhead press (existing)
  {
    meta: {
      slug: "overhead_press",
      name: "Overhead Press",
      aliases: ["overhead press", "shoulder press", "ohp", "military press", "strict press"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["triceps", "traps"],
      equipment: ["barbell", "dumbbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall with the weight racked at your shoulders and your feet about hip-width.",
        "Brace your core and keep your ribs stacked over your hips.",
        "Press the weight straight overhead until your arms are locked out.",
        "Lower under control back to your shoulders, then repeat.",
      ],
      formPoints: [
        "Press in a straight line to a full overhead lockout each rep.",
        "Keep your ribs down so you don't lean back to finish the press.",
        "Move at a steady pace up and down rather than heaving the weight.",
        "Finish with the weight balanced over your shoulders.",
      ],
      commonMistakes: [
        "Leaning back and turning the press into an incline push.",
        "Cutting the lockout short at the top.",
        "Using leg drive to bounce the weight up.",
      ],
      romGuideline: "Shoulders to a full overhead lockout; elbow ~80° racked to ~170° at the top.",
      tutTarget: [2, 4],
    },
    def: {
      id: "overhead-press",
      name: "Overhead Press",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells", "Barbell"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Front view, shoulders and arms visible",
      setupCue: "Face the camera with weights at your shoulders.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 82,
      activeAngle: 172,
      minRepFraction: 0.8,
      formChecks: [
        torsoStillCheck("Keep your ribs down — don't lean back.", 20),
        depthCheck("Press all the way up until your arms are straight.", 0.8),
      ],
      focus: ["lockout", "control", "tempo"],
      reviewCue: "Finish each rep locked out with the weight over your shoulders.",
    },
  },
  // ---------------------------------------------------------------- lateral raise (existing)
  {
    meta: {
      slug: "lateral_raise",
      name: "Lateral Raise",
      aliases: ["lateral raise", "side raise", "dumbbell lateral raise", "side lateral"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["traps"],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall with a dumbbell in each hand at your sides.",
        "Keep a slight bend in your elbows and lead with them.",
        "Raise your arms out to the sides until they reach about shoulder height.",
        "Lower under control back to your sides, then repeat.",
      ],
      formPoints: [
        "Lift out to about shoulder height rather than swinging higher.",
        "Lead with your elbows so the delts do the work.",
        "Keep your torso still instead of rocking the weight up.",
        "Control the lowering phase on every rep.",
      ],
      commonMistakes: [
        "Swinging the torso to throw the weight up.",
        "Lifting well past shoulder height and shrugging.",
        "Dropping the weights quickly instead of lowering them.",
      ],
      romGuideline: "Arms to about shoulder height; abduction from ~14° at rest to ~88° at the top.",
      tutTarget: [1, 3],
    },
    def: {
      id: "lateral-raise",
      name: "Lateral Raise",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Front view, both arms visible",
      setupCue: "Face the camera with arms at your sides.",
      keyJoints: ["hip", "shoulder", "elbow"],
      measure: abductionMeasure,
      restAngle: 14,
      activeAngle: 88,
      minRepFraction: 0.62,
      formChecks: [
        topHeightCheck(
          "Lift to shoulder height, no higher.",
          (pose) => abductionMeasure(pose)?.angle ?? null,
          104,
        ),
        torsoStillCheck("No swinging — control it up and down.", 20),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Lead with your elbows and stop at shoulder height.",
    },
  },
  // ---------------------------------------------------------------- front raise
  {
    meta: {
      slug: "front_raise",
      name: "Front Raise",
      aliases: ["front raise", "dumbbell front raise", "anterior raise"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["traps"],
      equipment: ["dumbbell"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Stand tall with a dumbbell in each hand resting in front of your thighs.",
        "Keep a slight bend in your elbows and your torso steady.",
        "Raise your arms straight in front of you to about shoulder height.",
        "Lower under control back to the start, then repeat.",
      ],
      formPoints: [
        "Lift to about shoulder height rather than swinging higher.",
        "Keep your torso still so the front delts do the work.",
        "Move at a steady pace both up and down.",
        "Own a consistent range on every rep.",
      ],
      commonMistakes: [
        "Rocking the torso to swing the weight up.",
        "Lifting well past shoulder height.",
        "Letting the weight drop quickly on the way down.",
      ],
      romGuideline: "Arms to about shoulder height in front; raise from ~12° at rest to ~88° at the top.",
      tutTarget: [1, 3],
    },
    def: {
      id: "front-raise",
      name: "Front Raise",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Front view, both arms visible",
      setupCue: "Face the camera with weights resting in front of your thighs.",
      keyJoints: ["hip", "shoulder", "elbow"],
      measure: abductionMeasure,
      restAngle: 12,
      activeAngle: 88,
      minRepFraction: 0.6,
      formChecks: [
        topHeightCheck(
          "Lift to shoulder height, no higher.",
          (pose) => abductionMeasure(pose)?.angle ?? null,
          104,
        ),
        torsoStillCheck("Keep your torso still — no swinging.", 20),
      ],
      focus: ["range", "control", "tempo"],
      reviewCue: "Raise to shoulder height and lower with control each rep.",
    },
  },
  // ---------------------------------------------------------------- arnold press
  {
    meta: {
      slug: "arnold_press",
      name: "Arnold Press",
      aliases: ["arnold press", "rotating shoulder press"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["triceps", "traps"],
      equipment: ["dumbbell"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "external",
      instructions: [
        "Sit or stand tall holding dumbbells in front of your shoulders, palms facing you.",
        "Brace your core and keep your ribs stacked over your hips.",
        "Rotate your palms out as you press the weights straight overhead to lockout.",
        "Reverse the rotation as you lower under control, then repeat.",
      ],
      formPoints: [
        "Press to a full overhead lockout on each rep.",
        "Keep your ribs down so you don't lean back to finish.",
        "Rotate smoothly rather than flinging the weights around.",
        "Control the weights back to the start position.",
      ],
      commonMistakes: [
        "Leaning back to muscle the weight overhead.",
        "Rushing the rotation and losing control.",
        "Stopping short of a full lockout.",
      ],
      romGuideline: "Shoulders to a full overhead lockout; elbow ~60° in front to ~170° at the top.",
      tutTarget: [2, 4],
    },
    def: {
      id: "arnold-press",
      name: "Arnold Press",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, shoulders and arms visible",
      setupCue: "Face the camera with weights in front of your shoulders.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 60,
      activeAngle: 172,
      minRepFraction: 0.75,
      formChecks: [
        torsoStillCheck("Keep your ribs down — don't lean back.", 20),
        depthCheck("Press all the way up until your arms are straight.", 0.75),
      ],
      focus: ["lockout", "control", "tempo"],
      reviewCue: "Finish each rep locked out overhead and control the way down.",
    },
  },
  // ---------------------------------------------------------------- dumbbell shoulder press
  {
    meta: {
      slug: "dumbbell_shoulder_press",
      name: "Dumbbell Shoulder Press",
      aliases: ["dumbbell shoulder press", "seated dumbbell press", "db shoulder press"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["triceps", "traps"],
      equipment: ["dumbbell", "bench"],
      difficulty: "beginner",
      tier: 1,
      loadType: "external",
      instructions: [
        "Sit on a bench with dumbbells racked at your shoulders, palms facing forward.",
        "Brace your core and keep your ribs stacked over your hips.",
        "Press the weights straight overhead until your arms are locked out.",
        "Lower under control back to your shoulders, then repeat.",
      ],
      formPoints: [
        "Press to a full overhead lockout each rep.",
        "Keep your ribs down and your back supported rather than arching.",
        "Move at a steady pace up and down.",
        "Finish with the weights balanced over your shoulders.",
      ],
      commonMistakes: [
        "Arching the back to push the weight up.",
        "Cutting the lockout short at the top.",
        "Letting the weights drop on the way down.",
      ],
      romGuideline: "Shoulders to a full overhead lockout; elbow ~78° racked to ~170° at the top.",
      tutTarget: [2, 4],
    },
    def: {
      id: "dumbbell-shoulder-press",
      name: "Dumbbell Shoulder Press",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells", "Bench"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 10, sets: 3 },
      tempo: "2-1-2-0",
      camera: "Front view, shoulders and arms visible",
      setupCue: "Face the camera with weights racked at your shoulders.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 78,
      activeAngle: 172,
      minRepFraction: 0.78,
      formChecks: [
        torsoStillCheck("Keep your ribs down — don't arch to press.", 20),
        depthCheck("Press all the way up until your arms are straight.", 0.78),
      ],
      focus: ["lockout", "control", "tempo"],
      reviewCue: "Finish each rep locked out with the weights over your shoulders.",
    },
  },
  // ---------------------------------------------------------------- pike push-up
  {
    meta: {
      slug: "pike_push_up",
      name: "Pike Push-Up",
      aliases: ["pike push up", "pike push-up", "pike press"],
      primaryMuscles: ["shoulders"],
      secondaryMuscles: ["triceps", "traps"],
      equipment: ["bodyweight"],
      difficulty: "intermediate",
      tier: 1,
      loadType: "bodyweight",
      instructions: [
        "Start in a push-up position, then walk your feet in and lift your hips into an inverted V.",
        "Set your hands a little wider than your shoulders with your head between your arms.",
        "Bend your elbows to lower the top of your head toward the floor.",
        "Press back up until your arms are straight, then repeat.",
      ],
      formPoints: [
        "Keep your hips high so the shoulders take the load.",
        "Lower your head under control toward the floor between your hands.",
        "Press back to straight arms on each rep.",
        "Move at a steady pace rather than dropping down.",
      ],
      commonMistakes: [
        "Letting the hips drop so it becomes a regular push-up.",
        "Cutting the range short at the bottom.",
        "Rushing the descent instead of controlling it.",
      ],
      romGuideline: "Head toward the floor between the hands; elbow ~85° at the bottom to straight at the top.",
      tutTarget: [2, 4],
    },
    def: {
      id: "pike-push-up",
      name: "Pike Push-Up",
      category: "push",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Bodyweight"],
      mode: "rep",
      view: "side",
      unilateral: false,
      target: { reps: 8, sets: 3 },
      tempo: "2-1-1-0",
      camera: "Side view — shoulders, elbows, and wrists visible",
      setupCue: "Set up side-on in an inverted-V pike position.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 165,
      activeAngle: 88,
      minRepFraction: 0.65,
      formChecks: [
        depthCheck("Lower a little more — head toward the floor.", 0.65),
      ],
      focus: ["depth", "control", "tempo"],
      reviewCue: "Keep the hips high and lower with control each rep.",
    },
  },
  // ---------------------------------------------------------------- shrug (tier 2)
  // Tier 2: a traps shrug has a very small range of motion (a short vertical
  // shoulder lift) that a single camera can count but can't judge for quality
  // without inventing precision, so we count reps and skip form checks.
  {
    meta: {
      slug: "shrug",
      name: "Shrug",
      aliases: ["shrug", "barbell shrug", "dumbbell shrug", "trap shrug"],
      primaryMuscles: ["traps"],
      secondaryMuscles: ["forearms"],
      equipment: ["dumbbell", "barbell"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Stand tall holding the weight at arm's length by your sides or in front.",
        "Keep your arms straight and your chest up.",
        "Lift your shoulders straight up toward your ears as high as you can.",
        "Lower under control back to the start, then repeat.",
      ],
      formPoints: [
        "Lift the shoulders straight up rather than rolling them.",
        "Keep your arms straight so the traps do the work.",
        "Pause briefly at the top for a strong squeeze.",
        "Lower under control on every rep.",
      ],
      commonMistakes: [
        "Rolling the shoulders instead of lifting straight up.",
        "Bending the elbows to help lift the weight.",
        "Rushing the reps with little range.",
      ],
      romGuideline: "Shoulders lifted straight up toward the ears through a short, controlled range.",
      tutTarget: [1, 3],
    },
    def: {
      id: "shrug",
      name: "Shrug",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Dumbbells", "Barbell"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "1-1-1-0",
      camera: "Front view, shoulders and neck visible",
      setupCue: "Face the camera with the weight at your sides.",
      keyJoints: ["ear", "shoulder", "hip"],
      measure: angleMeasure("ear", "shoulder", "hip", "best"),
      restAngle: 150,
      activeAngle: 160,
      minRepFraction: 0.5,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Lift the shoulders straight up and pause at the top.",
    },
  },
  // ---------------------------------------------------------------- upright row (tier 2)
  // Tier 2: the pull can be counted from the front, but elbow-height and
  // shoulder-position form judgment isn't reliable enough from one camera.
  {
    meta: {
      slug: "upright_row",
      name: "Upright Row",
      aliases: ["upright row", "barbell upright row", "cable upright row"],
      primaryMuscles: ["shoulders", "traps"],
      secondaryMuscles: ["biceps"],
      equipment: ["barbell", "dumbbell", "cable"],
      difficulty: "intermediate",
      tier: 2,
      loadType: "external",
      instructions: [
        "Stand tall holding the weight at arm's length in front of your thighs.",
        "Keep the weight close to your body as you pull.",
        "Lead with your elbows to draw the weight up toward your upper chest.",
        "Lower under control back to the start, then repeat.",
      ],
      formPoints: [
        "Lead with the elbows and keep the weight close to your body.",
        "Pull to about upper-chest height on each rep.",
        "Keep your torso tall rather than swinging back.",
        "Lower under control every rep.",
      ],
      commonMistakes: [
        "Letting the weight drift away from the body.",
        "Swinging the torso to help the pull.",
        "Rushing the reps with a short range.",
      ],
      romGuideline: "Weight pulled to about upper-chest height with the elbows leading.",
      tutTarget: [1, 3],
    },
    def: {
      id: "upright-row",
      name: "Upright Row",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Barbell", "Dumbbells", "Cable"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 12, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Front view, torso and arms visible",
      setupCue: "Face the camera with the weight in front of your thighs.",
      keyJoints: ["hip", "shoulder", "elbow"],
      measure: abductionMeasure,
      restAngle: 14,
      activeAngle: 70,
      minRepFraction: 0.6,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Lead with the elbows and keep the weight close on each rep.",
    },
  },
  // ---------------------------------------------------------------- face pull (tier 2)
  // Tier 2: a single camera can count the pull, but a real rear-delt form
  // judgment (elbow path, shoulder-blade action) would be fake precision.
  {
    meta: {
      slug: "face_pull",
      name: "Face Pull",
      aliases: ["face pull", "cable face pull", "band face pull"],
      primaryMuscles: ["shoulders", "traps"],
      secondaryMuscles: ["biceps"],
      equipment: ["cable", "band"],
      difficulty: "beginner",
      tier: 2,
      loadType: "external",
      instructions: [
        "Set a cable or band at about face height and grip each end.",
        "Step back to take the slack out and keep your chest up.",
        "Pull the handles toward your face, leading with your elbows out wide.",
        "Return under control to the start, then repeat.",
      ],
      formPoints: [
        "Lead with your elbows and pull toward your face.",
        "Keep your torso tall rather than leaning back.",
        "Pause briefly at the end of the pull.",
        "Return under control on every rep.",
      ],
      commonMistakes: [
        "Leaning back to yank the handles in.",
        "Dropping the elbows so it turns into a row.",
        "Rushing through with a short range.",
      ],
      romGuideline: "Handles drawn toward the face with the elbows leading out wide.",
      tutTarget: [1, 3],
    },
    def: {
      id: "face-pull",
      name: "Face Pull",
      category: "pull",
      dbCategory: "other",
      dbSlug: null,
      equipment: ["Cable", "Band"],
      mode: "rep",
      view: "front",
      unilateral: false,
      target: { reps: 15, sets: 3 },
      tempo: "1-1-2-0",
      camera: "Front view, shoulders and arms visible",
      setupCue: "Face the camera with the cable or band at face height.",
      keyJoints: elbowTriplet,
      measure: angleMeasure("shoulder", "elbow", "wrist", "best"),
      restAngle: 160,
      activeAngle: 75,
      minRepFraction: 0.55,
      formChecks: [],
      focus: ["range", "control", "tempo"],
      reviewCue: "Lead with the elbows and pause at the end of each pull.",
    },
  },
];
